### ISSUE TITLE
非常感谢您的工作，想问下，训练部分什么时候放出来呢

### ISSUE THREAD

**Issue by xingfubj** [MegviiDetection/video_analyst#1]

**Comment by lzx1413** [comment]
The training code for GOT10k will be released in 2 days

**Comment by MARMOTatZJU** [comment]
@xingfubj Training code and models released a few minutes ago.

**Comment by xingfubj** [comment]
@MARMOTatZJU @lzx1413  Thank you for your quick reply.

**Comment by MARMOTatZJU** [comment]
The training code has been released. Issue closed.
