### ISSUE TITLE
unzip trackingNet

### ISSUE THREAD

**Issue by twotwo2** [MegviiDetection/video_analyst#102]
Thank you for providing the link to download the dataset. But I have some questions, how should I extract files from TEST.zip.001？Should I merge these files (TEST.zip.001/TEST.zip.002...) before unzip?

**Comment by lzx1413** [comment]
You merge files with `cat Test.zip* > Test.zip' firstly.  Then use `unzip` to extract the files.

**Comment by MARMOTatZJU** [comment]
@twotwo2 Here is a link in detail.
https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux

**Comment by twotwo2** [comment]
Thank you very much!
