### ISSUE TITLE
Designate GPU computing

### ISSUE THREAD

**Issue by yutliu** [MegviiDetection/video_analyst#104]
Can you tell me how to designate certain GPUs on a computer for calculation？

**Comment by MARMOTatZJU** [comment]
You can do that with CUDA visibility: 
```bash
CUDA_VISIBLE_DEVICES=2,3 python train.py
```
ref.: https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on

**Comment by yutliu** [comment]
Thanks!It works.
