### ISSUE TITLE
Both train-set and test-set in LaSOT are used during the training process.

### ISSUE THREAD

**Issue by xi-mao** [MegviiDetection/video_analyst#113]
https://github.com/MegviiDetection/video_analyst/blob/141f54d34cf6ceac59f6679bc101c4879271c196/experiments/siamfcpp/train/fulldata/siamfcpp_googlenet-trn-fulldata.yaml#L120

I notice a mistake. The above setting will make both train-set and test-set in LaSOT are used during the training process. This will lead a 59.0%  even higher in AUC in LaSOT.
This should change to ' subset: "train" '

**Comment by lzx1413** [comment]
The model trained with fulldata can only be tested on VOT and TrackingNet.  We only use Lasot train set while measuring the performance of LaSOT test set.

**Comment by MARMOTatZJU** [comment]
@xi-mao  [This config](https://github.com/MegviiDetection/video_analyst/blob/master/experiments/siamfcpp/train/lasot/siamfcpp_googlenet-trn.yaml) is for training & test on LaSOT.

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.
