### ISSUE TITLE
run 'siamfcpp_googlenet_votlt.yaml' and how to get classification scores

### ISSUE THREAD

**Issue by BridgeLee** [MegviiDetection/video_analyst#115]
I can run Python 3. / main successfully/ test.py  --config experiments/siamfcpp/test/vot/siamfcpp_ googlenet.yaml '
However, I can't run Python 3. / main successfully/ test.py  --config'experiences / siamfcpp / test / VOT / siamfcpp_ googlenet_ votlt.yaml '.The error is 'No such file or directory: '/SiamFC++/datasets/VOT2018LT/ list.txt. How to place vot2018LT.
Besides, if I want to get the classification scores in every video of VOT2018 dataset, what can i do?Thank you very much.

**Comment by lzx1413** [comment]
1. The result of vot2018lt is not satisfactory enough  and we are still refining it until  now.  I will update the structure of vot2018lt datasets today.
2. You can get the score by return it from [tracker](https://github.com/MegviiDetection/video_analyst/blob/5c5d79cd911cdc9aefda15101e4a77fdb72ad372/videoanalyst/pipeline/tracker_impl/siamfcpp_track.py#L260)

**Comment by BridgeLee** [comment]
Thank you very much and I have get the scores.
What's more, I have another question: in files of VOT2018 Result,some lines of txt files show'2 0 0 0 0 1', such as 'ant3_001.txt', from line 310 to315 and line from 349 to 354. And in these frame, I can't get the classification scores.  So what happen in these frames?

**Comment by lzx1413** [comment]
@BridgeLee  this means that these frames are used be the template image to restart the tracking in VOT test process.
