### ISSUE TITLE
Result problem about MODEL_ZOO

### ISSUE THREAD

**Issue by hekj** [MegviiDetection/video_analyst#117]
**I. Question**
I used the pre-trained  models from MODEL_ZOO for test on VOT2018, but got lower EAO than scores below.
![image](https://user-images.githubusercontent.com/17741857/87249661-dff70a80-c492-11ea-9fa5-c8c9e19fce9b.png)
I wonder how I can fix that. Thank you!

**II. Useful information**
**1. Here is my EAO scores**
**(1) torch1.4.0 ( with default cudatoolkit installed by conda)**
![image](https://user-images.githubusercontent.com/17741857/87249860-2e58d900-c494-11ea-841b-b285515a452b.png)
![image](https://user-images.githubusercontent.com/17741857/87249863-331d8d00-c494-11ea-8a19-85fc973cb7d3.png)
**(2) torch1.1.0( with default cudatoolkit installed by conda)**
![image](https://user-images.githubusercontent.com/17741857/87249891-5ba58700-c494-11ea-8f5b-80f01f815f4b.png)
![image](https://user-images.githubusercontent.com/17741857/87249892-5ba58700-c494-11ea-966c-b67a574c7b1e.png)

**2. Here is my version of package( output of 'pip freeze' )**
**(1) for torch1.4.0**
absl-py==0.9.0
aiocontextvars==0.2.2
astroid==2.4.2
backcall==0.2.0
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
colorama==0.3.7
contextvars==2.4
cycler==0.10.0
Cython==0.27.3
decorator==4.4.2
future==0.18.2
google-auth==1.18.0
google-auth-oauthlib==0.4.1
grpcio==1.30.0
idna==2.10
imageio==2.9.0
immutables==0.14
importlib-metadata==1.7.0
ipython==7.16.1
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.17.1
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
llvmlite==0.32.1
loguru==0.4.1
Markdown==3.2.2
matplotlib==3.2.2
mccabe==0.6.1
networkx==2.4
numba==0.45.0
numpy==1.19.0
oauthlib==3.1.0
opencv-python==4.3.0.36
pandas==0.25.3
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
prompt-toolkit==3.0.3
protobuf==3.12.2
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.1
Pygments==2.6.1
pylint==2.5.3
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-image==0.17.2
scipy==1.2.1
Shapely==1.7.0
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tifffile==2020.7.4
toml==0.10.1
torch==1.4.0
torchvision==0.5.0
tqdm==4.47.0
traitlets==4.3.3
typed-ast==1.4.1
urllib3==1.25.9
wcwidth==0.2.5
Werkzeug==1.0.1
wget==3.2
wrapt==1.12.1
yacs==0.1.7
yapf==0.28.0
zipp==3.1.0
**(2) for torch1.1.0**
absl-py==0.9.0
aiocontextvars==0.2.2
astroid==2.4.2
backcall==0.2.0
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
colorama==0.3.7
contextvars==2.4
cycler==0.10.0
Cython==0.27.3
decorator==4.4.2
future==0.18.2
google-auth==1.18.0
google-auth-oauthlib==0.4.1
grpcio==1.30.0
idna==2.10
imageio==2.9.0
immutables==0.14
importlib-metadata==1.7.0
ipython==7.16.1
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.17.1
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
llvmlite==0.32.1
loguru==0.4.1
Markdown==3.2.2
matplotlib==3.2.2
mccabe==0.6.1
networkx==2.4
numba==0.45.0
numpy==1.19.0
oauthlib==3.1.0
opencv-python==4.3.0.36
pandas==1.0.5
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
prompt-toolkit==3.0.5
protobuf==3.12.2
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.1
Pygments==2.6.1
pylint==2.5.3
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-image==0.17.2
scipy==1.2.1
Shapely==1.7.0
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tifffile==2020.7.4
toml==0.10.1
torch==1.1.0
torchvision==0.3.0
tqdm==4.47.0
traitlets==4.3.3
typed-ast==1.4.1
urllib3==1.25.9
wcwidth==0.2.5
Werkzeug==1.0.1
wget==3.2
wrapt==1.12.1
yacs==0.1.7
yapf==0.28.0
zipp==3.1.0

**Comment by MARMOTatZJU** [comment]
@hekj Hello. Consider changing opencv-python version to 3.4.X.X (e.g. 3.4.1.15). 

I find that the opencv-python version indicated in our requirements.txt is not the same as is when we produced the result on VOT2018. It should be a version near 3.4.X.X, but after a rough climbing through the git tree, I do not found that. I plan to give a dockerfile from which the docker image built should reproduce the results without further changes of environment. Rather, VOT benchmark is sensitive to too many factors. Even the version of opencv-python (in this case) may change the EAO.

BTW, what is "default cudatoolkit installed by conda"? What is its version?

**Comment by hekj** [comment]
**@MARMOTatZJU**  Thanks for your answer. I have tried a few versions of 'opencv-python==3.4.X.X' but got no improvement on VOT2018. Maybe there are some others causes.  Look forward to your docker image!
For the cudatoolkit, I am sorry I have made a wrong statement. In fact, my version of cuda used by torch is '10.1', but I did not install it directly. I try to find cuda's directory but failed. I assume that the cuda is installed by 'pip' defaultly when 'pip install torch torchvision' or other commands are executed.

**Comment by MARMOTatZJU** [comment]
@hekj We provide dockerfile to build environment which can reproduce the exact result. Please wait for the completion of this PR: https://github.com/MegviiDetection/video_analyst/pull/121

**Comment by hekj** [comment]
OK，thank you!

**Comment by hekj** [comment]
OK，thank you!
