### ISSUE TITLE
Using first frame

### ISSUE THREAD

**Issue by BridgeLee** [MegviiDetection/video_analyst#123]
SiamFC + + does not seem to use the data of the first frame to fine tune the model. What is the reason? Is it because there is enough training data, so the effect of fine-tuning is not enough?

**Comment by MARMOTatZJU** [comment]
@BridgeLee We investigate the principles for the architecture design of siamese tracker instead of tracking pipeline. So we keep the same setting (no finetune on the first frame for siamese tracker) w.r.t. to existing methods.

**Comment by MARMOTatZJU** [comment]
@BridgeLee Issue closed as it's been a long time without further reply. Wish that you've already fixed your issue. Feel free to reopen for further help
