### ISSUE TITLE
About 'state score' in SAT

### ISSUE THREAD

**Issue by blessingforever** [MegviiDetection/video_analyst#130]
I'm searching for the implementation of 'state score' which conisists of a 'confidence score' and a ' concentration score', as stated in《State-Aware Tracker for Real-Time Video Object Segmentation》. But it seems that this part is not included in current repository  . Can you tell me the path to that or will it be added some day? Especially, I wonder how the 'concentration score' is calculated.

**Comment by lzx1413** [comment]
@blessingforever  The state score is here https://github.com/MegviiDetection/video_analyst/blob/01b7ad278b828a3f7ff7a0488c5ca8f055240192/videoanalyst/pipeline/segmenter_impl/sat_pipeline.py#L320
