### ISSUE TITLE
about sat resume trian

### ISSUE THREAD

**Issue by zyx1213271098** [MegviiDetection/video_analyst#137]
Thank you for your great work！I am very inspired.
I get an “KeyError: 'model_state_dict' ”error when I use the pre-trained model (sat_res50_davis17_b81fa.pkl) to resume train SAT.
How do I use the pre-trained model?
Thanks again！

**Comment by lzx1413** [comment]
@zyx1213271098 
Because we remove information about other options such as optimizer_state_dict and model_state_dict when release the model. The released model only have the params of  the network so you can use it to init the task model like this in the config yaml
```
 task_model:
        name: "SatVOS"
        pretrain_model_path: "xxxxx.pkl"
```

**Comment by zyx1213271098** [comment]
Thanks a lot, it worked！
