### ISSUE TITLE
Where are the feature maps after backbone?

### ISSUE THREAD

**Issue by BridgeLee** [MegviiDetection/video_analyst#139]
If I want to get the feature maps of  images after they pass through the backbone, which variable should I save?

**Comment by lzx1413** [comment]
https://github.com/MegviiDetection/video_analyst/blob/1322e45384ba138e759ad4864c3e31d3b465f2d9/videoanalyst/model/task_model/taskmodel_impl/siamese_track.py#L64 for train and https://github.com/MegviiDetection/video_analyst/blob/1322e45384ba138e759ad4864c3e31d3b465f2d9/videoanalyst/model/task_model/taskmodel_impl/siamese_track.py#L159 for track test
