### ISSUE TITLE
SiamFCpp tracker pretrained model download link 

### ISSUE THREAD

**Issue by huchenjie339** [MegviiDetection/video_analyst#140]
SiamFCpp tracker download is not stable on Weiyun. I downloaded it several times on Tencent Weiyun and failed. Could you provide a Baidu cloud disk link?

**Comment by lzx1413** [comment]
@huchenjie339  I will update one copy on BaiDu cloud today.

**Comment by MARMOTatZJU** [comment]
@huchenjie339 Please do not reply on BaiduDisk as from our practice, Baidu can ban such sharing link very often. Consider using GoogleDrive's link?

**Comment by lzx1413** [comment]
@huchenjie339 链接：https://pan.baidu.com/s/11BfdoFmdagt9IRP41wXsEA 
提取码：qhmo You can try this link now

**Comment by huchenjie339** [comment]
I just tried and Baidu cloud disk link was invalid.Please send link to my email, thank you.2552981549@qq.com

**Comment by lzx1413** [comment]
done

**Comment by gaojian66** [comment]
> @huchenjie339 链接：https://pan.baidu.com/s/11BfdoFmdagt9IRP41wXsEA
> 提取码：qhmo You can try this link now

I just tried and Baidu cloud disk link was invalid.Please send link to my email, thank you.1332300084@qq.com

**Comment by lzx1413** [comment]
@gaojian66  sent.

**Comment by tangchuanming1995** [comment]
> @huchenjie339 链接：https://pan.baidu.com/s/11BfdoFmdagt9IRP41wXsEA
> 提取码：qhmo You can try this link now

I just tried and Baidu cloud disk link was invalid.Please send link to my email, thank you 。。1079749670@qq.com

**Comment by lzx1413** [comment]
> > @huchenjie339 链接：https://pan.baidu.com/s/11BfdoFmdagt9IRP41wXsEA
> > 提取码：qhmo You can try this link now
> 
> I just tried and Baidu cloud disk link was invalid.Please send link to my email, thank you 。。[1079749670@qq.com](mailto:1079749670@qq.com)

sent

**Comment by tangchuanming1995** [comment]
> > > @huchenjie339 链接：https://pan.baidu.com/s/11BfdoFmdagt9IRP41wXsEA
> > > 提取码：qhmo You can try this link now
> > 
> > 
> > I just tried and Baidu cloud disk link was invalid.Please send link to my email, thank you 。。[1079749670@qq.com](mailto:1079749670@qq.com)
> 
> sent

thanks~

**Comment by MARMOTatZJU** [comment]
@tangchuanming1995  Issue closed as it's been a long time without further reply. Wish that you've already fixed your issue. Feel free to reopen for further help.
