### ISSUE TITLE
Problems when training

### ISSUE THREAD

**Issue by pvoigtlaender** [MegviiDetection/video_analyst#145]
Hi,

thanks for sharing the code!

When I try to train using 
`python3 ./main/dist_train_sat.py --config 'experiments/sat/train/sat_res50_davis17.yaml`

I get an attribute error at
`model = model_builder.build(task, task_cfg.model)`
in dist_train.py

When I replace that line by 
`model = model_builder.build(task, task_cfg['segmenter'])`
then I get
`AttributeError: 'NoneType' object has no attribute 'eval'`
at
`self.tracker.eval()`
in distributed_sat_trainer.py  (the tracker is None).

**Comment by lzx1413** [comment]
@pvoigtlaender  It seems that `model = model_builder.build(task, taks_cfg.model)` is in dist_train.py while we train sat with dist_train_sat.py?

**Comment by pvoigtlaender** [comment]
Gotcha!
Thx, it's working now :)
