### ISSUE TITLE
About centerness_loss and  bce_loss

### ISSUE THREAD

**Issue by jianjiandandande** [MegviiDetection/video_analyst#151]
I want to know the role of multi_bceloss,  does it relate to centerness_loss
![image](https://user-images.githubusercontent.com/15951818/95478593-4a4d1780-09bc-11eb-868b-84d62e6bf015.png)

**Comment by lzx1413** [comment]
@jianjiandandande  no, it is used in SAT for segmentation.

**Comment by jianjiandandande** [comment]
ok, thanks
