### ISSUE TITLE
SAT segmentor is not accessable

### ISSUE THREAD

**Issue by lqiang2003cn** [MegviiDetection/video_analyst#152]
the baidu yun link is not accessible , can you give me a new link?
my email is : randycoq@163.com
 thanks a lot!

**Comment by lzx1413** [comment]
done

**Comment by zhangyunming** [comment]
635781993@qq.com thanks, sat

**Comment by lichuntang** [comment]
Could you give me a link of SAT segmentor, 1358552539@qq.com, thanks a lot!

**Comment by shiragit** [comment]
can you please publish a new link for it? thanks

**Comment by lzx1413** [comment]
@shiragit  the google drive link is here https://drive.google.com/open?id=1UXshq4k9WKx4hNkdpOagJLXPR57ZkBkg

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
