### ISSUE TITLE
Add new function.

### ISSUE THREAD

**Issue by zxyjfj** [MegviiDetection/video_analyst#153]
Could you add a demo file just like the [SiamMask](https://github.com/foolwood/SiamMask/blob/master/tools/demo.py), thus I can apply the `SAT` model to extract the mask image from other videos.

**Comment by lzx1413** [comment]
@zxyjfj  I will add one demo code soon and you can try to implement it with the reference of sot_video.py

**Comment by zhangyunming** [comment]
@zxyjfj when？ wait in hope.

**Comment by lzx1413** [comment]
@zxyjfj 
@zhangyunming 
the demo code is here https://github.com/MegviiDetection/video_analyst/blob/sat_demo/demo/main/video/sat_video.py
we will merge it soon
