### ISSUE TITLE
Can you explain in detail the testing work on NVIDIA nano.

### ISSUE THREAD

**Issue by najingligong1111** [MegviiDetection/video_analyst#155]
Can you explain in detail the testing work on NVIDIA nano.

**Comment by lzx1413** [comment]
@najingligong1111  we have not tested it on NVIDIA nano. You can try to transfer the model to trt or install the pyotch on nvidia nao

**Comment by MARMOTatZJU** [comment]
@najingligong1111 Just install the requirements as usual on your Jeston Nano, then run the tracker. 
I recommend you the official forum of [NVIDIA Jeston](https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70) as I found it really useful.

**Comment by MARMOTatZJU** [comment]
@najingligong1111 Issue closed as it's been a long time without further reply. Wish that you've already fixed your issue. Feel free to reopen for further consulation.
