### ISSUE TITLE
using resnet as backbone in SiamFC++

### ISSUE THREAD

**Issue by TragedyN** [MegviiDetection/video_analyst#157]
Thank you for your great work in advance!
I see you add resnet18 and resnet50 in the backbone file, so I wonder if you trained models base on this two and how this the performence ? Thx again.
ps: I am mainly curious about resnet18

**Comment by lzx1413** [comment]
Sorry, we do not try res18 in siamfc++. According to siamrpn and dimp, there may be some little performance drop with res18 compared with larger backbone such as res50.

**Comment by TragedyN** [comment]
I see. Thx for your reply
