### ISSUE TITLE
Results problem about SAT

### ISSUE THREAD

**Issue by Jieqianyu** [MegviiDetection/video_analyst#158]
Hi! I used your training code to train SAT model with 2 GPU, but the results were a little lower than those in the model zoo and in the paper. The training datasets are COCO, YouTube-VOS and DAVIS.
![image](https://user-images.githubusercontent.com/39148698/98514556-9aade280-22a4-11eb-8687-0dfb7a71d64e.png)

**Comment by Jieqianyu** [comment]
Do you have better parameters for 2 GPU?

**Comment by lzx1413** [comment]
We trained the model with batch size 128. Maybe you need tuning the lr  for 2gpus . Sorry we did not test the training process on 2 gpus

**Comment by Jieqianyu** [comment]
Thanks!
