### ISSUE TITLE
Test SAT

### ISSUE THREAD

**Issue by gruossomonica** [MegviiDetection/video_analyst#159]
Hi, thank you for your work. I tested the VOS approach on Windows, with GTX 1080 GPU card, cuda 10.1, cuDNN v8.0.5 (November 9th, 2020), python 3.6.12, pytorch 1.7.0 (with cudatoolkit 10.1).
I used `sat_res50-davis17.yaml` config. I set `save_patch: &save_patch True` (line 59), `save_video: True` (line 74), `device_num: 1` (line 72) because I used only one GPU.
At the end of the test phase, I checked `log` folder. There were 4 subfolders: 

- `dump` is empty
- `patches` contains subfolders (one for each element in val.txt file in `DAVIS/ImageSets/2017`) with predicted masks overlapping the image patches
- `results_multi` contains empty subfolders (one for each element in val.txt file in `DAVIS/ImageSets/2017`)
- `save_video` contains .avi videos (one for each element in val.txt file in `DAVIS/ImageSets/2017`)

Here the last lines iIn my anaconda prompt:

```
Evaluating sequences for the semi-supervised task...
----------
2017
----------
 bike-packing frame DAVIS\Annotations\480p\bike-packing\00001 not found!                                          | 0/30 [00:00<?, ?it/s]
The frames have to be indexed PNG files placed inside the corespondent sequence folder.
The indexes have to match with the initial frame.
IOError: No such file or directory
  0%|                                                                                                                    | 0/30 [00:00<?, ?it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [06:23<00:00, 12.78s/it]
```

What went wrong? What can I change?
Looking forward to your reply and suggestions.
Thanks again.

Monica Gruosso

**Comment by gruossomonica** [comment]
Sorry, I have another question. Can I test your approach on my unlabeled videos? What should I change in code, config, etc?

Best regards,

Monica Gruosso

**Comment by lzx1413** [comment]
> Sorry, I have another question. Can I test your approach on my unlabeled videos? What should I change in code, config, etc?
> 
> Best regards,
> 
> Monica Gruosso

You can test the unlabeled videos by this script https://github.com/MegviiDetection/video_analyst/blob/dev/demo/main/video/sat_video.py

**Comment by lzx1413** [comment]
> Hi, thank you for your work. I tested the VOS approach on Windows, with GTX 1080 GPU card, cuda 10.1, cuDNN v8.0.5 (November 9th, 2020), python 3.6.12, pytorch 1.7.0 (with cudatoolkit 10.1).
> I used `sat_res50-davis17.yaml` config. I set `save_patch: &save_patch True` (line 59), `save_video: True` (line 74), `device_num: 1` (line 72) because I used only one GPU.
> At the end of the test phase, I checked `log` folder. There were 4 subfolders:
> 
> * `dump` is empty
> * `patches` contains subfolders (one for each element in val.txt file in `DAVIS/ImageSets/2017`) with predicted masks overlapping the image patches
> * `results_multi` contains empty subfolders (one for each element in val.txt file in `DAVIS/ImageSets/2017`)
> * `save_video` contains .avi videos (one for each element in val.txt file in `DAVIS/ImageSets/2017`)
> 
> Here the last lines iIn my anaconda prompt:
> 
> ```
> Evaluating sequences for the semi-supervised task...
> ----------
> 2017
> ----------
>  bike-packing frame DAVIS\Annotations\480p\bike-packing\00001 not found!                                          | 0/30 [00:00<?, ?it/s]
> The frames have to be indexed PNG files placed inside the corespondent sequence folder.
> The indexes have to match with the initial frame.
> IOError: No such file or directory
>   0%|                                                                                                                    | 0/30 [00:00<?, ?it/s]
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [06:23<00:00, 12.78s/it]
> ```
> 
> What went wrong? What can I change?
> Looking forward to your reply and suggestions.
> Thanks again.
> 
> Monica Gruosso

What's you dataset structure of davis17 , we assume that the structure should be like in the https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/VOS_SETUP.md

**Comment by gruossomonica** [comment]
> What's you dataset structure of davis17 , we assume that the structure should be like in the https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/VOS_SETUP.md

I downloaded the DAVIS dataset from https://davischallenge.org/davis2017/code.html. In  particular, the semisupervised `TrainVal - Images and Annotations 408p` data.
The structure of the folder is the following:

```
└── dataset
       ├──Annotations
       |        └── 408p
       ├── ImageSets
       |        ├── 2016
       |        |     ├── train.txt
       |        |     └── val.txt
       |        └── 2017
       |              ├── train.txt
       |              └── val.txt
       └── JPEGImages
                └── 408p
```
I just realized that in you [setup file](https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/VOS_SETUP.md) there is `480p_2016` subfolder in a the `Annotations` folder. 
Should I create it by checking what annotations are correct for davis 2016 or is the downloaded dataset wrong?
Thanks for the support.

Monica Gruosso

**Comment by lzx1413** [comment]
> > What's you dataset structure of davis17 , we assume that the structure should be like in the https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/VOS_SETUP.md
> 
> I downloaded the DAVIS dataset from https://davischallenge.org/davis2017/code.html. In particular, the semisupervised `TrainVal - Images and Annotations 408p` data.
> The structure of the folder is the following:
> 
> ```
> └── dataset
>        ├──Annotations
>        |        └── 408p
>        ├── ImageSets
>        |        ├── 2016
>        |        |     ├── train.txt
>        |        |     └── val.txt
>        |        └── 2017
>        |              ├── train.txt
>        |              └── val.txt
>        └── JPEGImages
>                 └── 408p
> ```
> 
> I just realized that in you [setup file](https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/VOS_SETUP.md) there is `480p_2016` subfolder in a the `Annotations` folder.
> Should I create it by checking what annotations are correct for davis 2016 or is the downloaded dataset wrong?
> Thanks for the support.
> 
> Monica Gruosso

the error occurs while trying to read the file from https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/evaluation/davis_benchmark/davis2017/results.py#L13, you can print this file and figure out which file is needed here.

**Comment by gruossomonica** [comment]
Thanks you @lzx1413! I will check asap!

**Comment by gruossomonica** [comment]
> the error occurs while trying to read the file from
> 
> https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/evaluation/davis_benchmark/davis2017/results.py#L13
> 
> , you can print this file path and figure out which file is needed here.

I printed root_dir, sequence, frame_id and mask_path. I got the following:
```
root_dir in Results class:  logs\DAVIS2017\sat_res50_davis17\baseline\results_multi              | 0/30 [00:00<?, ?it/s]
sequence in Results class:  bike-packing
frame_id in Results class:  DAVIS\Annotations\480p\bike-packing\00001
mask_path in Results class:  logs\DAVIS2017\sat_res50_davis17\baseline\results_multi\bike-packing\DAVIS\Annotations\480p\bike-packing\00001.png
```

But `logs\DAVIS2017\sat_res50_davis17\baseline\results_multi\bike-packing` was automatically created and is empty. Also  `logs\DAVIS2017\sat_res50_davis17\baseline\results_multi` was automatically created.
Which could be the correct root_dir, sequence, frame_id and mask_path?

**Comment by gruossomonica** [comment]
> the error occurs while trying to read the file from
> 
> https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/evaluation/davis_benchmark/davis2017/results.py#L13
> 
> , you can print this file path and figure out which file is needed here.

I printed root_dir, sequence, frame_id and mask_path. I got the following:
```
root_dir in Results class:  logs\DAVIS2017\sat_res50_davis17\baseline\results_multi
sequence in Results class:  bike-packing
frame_id in Results class:  DAVIS\Annotations\480p\bike-packing\00001
mask_path in Results class:  logs\DAVIS2017\sat_res50_davis17\baseline\results_multi\bike-packing\DAVIS\Annotations\480p\bike-packing\00001.png
```

But `logs\DAVIS2017\sat_res50_davis17\baseline\results_multi\bike-packing` was automatically created and is empty. Also  `logs\DAVIS2017\sat_res50_davis17\baseline\results_multi` was automatically created.
Which could be the correct root_dir, sequence, frame_id and mask_path?

**Comment by lzx1413** [comment]
> > the error occurs while trying to read the file from
> > https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/evaluation/davis_benchmark/davis2017/results.py#L13
> > 
> > , you can print this file path and figure out which file is needed here.
> 
> I printed root_dir, sequence, frame_id and mask_path. I got the following:
> 
> ```
> root_dir in Results class:  logs\DAVIS2017\sat_res50_davis17\baseline\results_multi
> sequence in Results class:  bike-packing
> frame_id in Results class:  DAVIS\Annotations\480p\bike-packing\00001
> mask_path in Results class:  logs\DAVIS2017\sat_res50_davis17\baseline\results_multi\bike-packing\DAVIS\Annotations\480p\bike-packing\00001.png
> ```
> 
> But `logs\DAVIS2017\sat_res50_davis17\baseline\results_multi\bike-packing` was automatically created and is empty. Also `logs\DAVIS2017\sat_res50_davis17\baseline\results_multi` was automatically created.
> Which could be the correct root_dir, sequence, frame_id and mask_path?

This folder should contain the segment result files named xxx.png. 
You can try to set the save_patch &save_video False(default value), Maybe there are some conflicts and I will fix it soon

**Comment by gruossomonica** [comment]
> This folder should contain the segment result files named xxx.png.
> You can try to set the save_patch &save_video False(default value), Maybe there are some conflicts and I will fix it soon

I tried, but the subfolders in `results_multi` are still empty.

**Comment by gruossomonica** [comment]
I can confirm that problems were caused by the Windows path name convention. I used `posixpath` insted of `os.path` to import `join` in [davis2017/davis.py](https://github.com/MegviiDetection/video_analyst/blob/master/videoanalyst/evaluation/davis_benchmark/davis2017/davis.py).
In addition, as indicated in the previous comment, I replaced the `glob` usage:

https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/evaluation/davis_benchmark/davis2017/davis.py#L76-L77
was replaced by
```
images_path = join(self.img_path, seq)
images = [join(images_path, name) for name in os.listdir(images_path) if name.endswith(".jpg")]
```
and
https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/evaluation/davis_benchmark/davis2017/davis.py#L82-L83
was replaced by 
```
masks_path = join(self.mask_path, seq)
masks = [join(masks_path, name) for name in os.listdir(masks_path) if name.endswith(".png")]
```

These changes fixed all the errors. 😀 
I hope my comments can help other Windows users too.
