### ISSUE TITLE
Could not load the Qt platform plugin?

### ISSUE THREAD

**Issue by vicdxxx** [MegviiDetection/video_analyst#160]
I run demo met this error

**Comment by lzx1413** [comment]
Our demo does not rely on Qt. Maybe you should re-check your installation of opencv

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.

**Comment by Meryl-Fang** [comment]
@vicdxxx I met this error too when running the sat demo. I think it might be related to the cv2, tried the commented out  opencv-python==4.1.0.25 in requirements.txt and it worked.
