### ISSUE TITLE
How to restore the results as mentioned in Paper?

### ISSUE THREAD

**Issue by Deepanshu-beep** [MegviiDetection/video_analyst#161]
@MARMOTatZJU @lzx1413 @lanhongvp @CMeteor How can restore the exact  results that is J,F values as mentioned in the paper?

**Comment by lzx1413** [comment]
@Deepanshu-beep  It is hard to align the model between pytorch and our internal framework， you can try to search the train parameters and test parameters to get better results.

**Comment by Deepanshu-beep** [comment]
@lzx1413 No I mean to say that, is the script for evaluating J,F values available in the code or do I need to refer some other repo for evaluating results?

**Comment by lzx1413** [comment]
@Deepanshu-beep  you can just run `python3 ./main/test.py --config 'experiments/sat/test/sat_res50-davis17.yaml'`. The result will be showed at the end.

**Comment by Deepanshu-beep** [comment]
Okay, Thanks for your support :)
