### ISSUE TITLE
bash ./tools/sat/test/test_DAVIS2017.sh  ModuleNotFoundError: No module named 'videoanalyst'

### ISSUE THREAD

**Issue by zxyyxzz** [MegviiDetection/video_analyst#165]
![image-20201216161342959](C:\Users\zxy\AppData\Roaming\Typora\typora-user-images\image-20201216161342959.png)

I have run:
    bash compile.sh

but when i run: bash ./tools/sat/test/test_DAVIS2017.sh
  the error exception.
`Traceback (most recent call last):
  File "./main/test.py", line 10, in <module>
    from videoanalyst.config.config import cfg as root_cfg
ModuleNotFoundError: No module named 'videoanalyst'`

Any solution about it?
Thanks

**Comment by zxyyxzz** [comment]
@lzx1413

**Comment by MARMOTatZJU** [comment]
@zxyyxzz Try following script for setup.
```
root_dir=path/to/video_analyst
export PYTHONPATH=$root_dir
```

**Comment by lzx1413** [comment]
please install this project according to https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/SETUP.md

**Comment by zxyyxzz** [comment]
> 
> 
> @zxyyxzz Try following script for setup.
> 
> ```
> root_dir=path/to/video_analyst
> export PYTHONPATH=$root_dir
> ```
Thanks !

**Comment by zxyyxzz** [comment]
> 
> 
> please install this project according to https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/SETUP.md

Thanks for your reply, it is really helpful, but now i still have a question about: i have downloaded siamfcpp,  but i don't find the other pretrained models in your baiduyun and tencent weiyun and google drive,  so where can i get res-50-imagenet-fff49.pkl, res-18-imagenet-7ccb1.pkl, sat_res50_davis17_2518a.pkl and sat_res18_davis17_7ccb1.pkl?
models
├── siamfcpp
    |── siamfcpp-alexnet-vot-md5_18fd31a2f94b0296c08fff9b0f9ad240.pkl
├── sat
    |── sat_res50_davis17_2518a.pkl
    |── sat_res18_davis17_7ccb1.pkl
├── resnet
    |── res-50-imagenet-fff49.pkl
    |── res-18-imagenet-7ccb1.pkl

**Comment by zxyyxzz** [comment]
@lzx1413 sorry  i find these pretrained models,  也许是我的网络不好，我下载下来的时候，掉了几个文件，我以为没有，不好意思
