### ISSUE TITLE
Segmentation fault (core dumped), exception, when i want to train SAT.

### ISSUE THREAD

**Issue by zxyyxzz** [MegviiDetection/video_analyst#166]
when i run :CUDA_VISIBLE_DEVICES=0 python3 ./main/dist_train_sat.py --config experiments/sat/train/sat_res18_davis17.yaml
`Segmentation fault (core dumped)` is occured.
test is ok, only train will exception this error.

Any solutions about it ?
Thanks very much

**Comment by zxyyxzz** [comment]
@lzx1413

**Comment by lzx1413** [comment]
what's the environment on your computer? system, version of python packages.

**Comment by zxyyxzz** [comment]
> 
> 
> what's the environment on your computer? system, version of python packages.

`Linux version 4.15.0-45-generic (buildd@lcy01-amd64-027) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #48~16.04.1-Ubuntu SMP`
python = 3.7.9
pytorch = 1.7.1
cuda = cuda11

**Comment by lzx1413** [comment]
where does this error happened. dataloader? trainer? Could you   paste the screen shot of this error?

**Comment by zxyyxzz** [comment]
> 
> 
> where does this error happened. dataloader? trainer? Could you paste the screen shot of this error?

when i run :CUDA_VISIBLE_DEVICES=0 python3 ./main/dist_train_sat.py --config experiments/sat/train/sat_res18_davis17.yaml
the errors occured immediately,
The all information in screen shot of this error as following:
`(STR) zhouxy@estar-Super-Server:~/code/video_analyst$ CUDA_VISIBLE_DEVICES=0 python3 ./main/dist_train_sat.py --config experiments/sat/train/sat_res18_davis17.yaml
Segmentation fault (core dumped)`

**Comment by lzx1413** [comment]
You can try to test the dataloader first. whether you can get the train data from the dataloader?

**Comment by zxyyxzz** [comment]
> 
> 
> You can try to test the dataloader first. whether you can get the train data from the dataloader?

yes, i reinstall my environment , and change version of some packages ,everthing is ok ,but now , if i only a  single GPU ,any methods to run vos？

**Comment by zxyyxzz** [comment]
> 
> 
> You can try to test the dataloader first. whether you can get the train data from the dataloader?

I just change the num_process to 1 in config file , is it correct?

**Comment by lzx1413** [comment]
> > You can try to test the dataloader first. whether you can get the train data from the dataloader?
> 
> I just change the num_process to 1 in config file , is it correct?, i feel confusing ,because i see the miou are all same(miou = 0.382) in every epoch, but the loss keeps dropping:
> 
> screen shot as following:
> `rack_fwd: 1.7e-01, segfwd: 3.8e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:35:51.128 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 30/1250 epoch 0 eta (1h 1m 9s) bs: 128 epoch 0, lr: 9.7e-04, multi_bceloss: 0.787, mean_iou: 0.382, data: 2.2e+00, track_fwd: 1.7e-01, segfwd: 4.3e-02, bwd: 1.7e-01, optim: 3.6e-01, max mem: 11955.4M 2020-12-20 09:35:52.020 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 31/1250 epoch 0 eta (0h 17m 10s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.770, mean_iou: 0.382, data: 3.1e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:28.921 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 32/1250 epoch 0 eta (12h 28m 7s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.769, mean_iou: 0.382, data: 3.6e+01, track_fwd: 1.7e-01, segfwd: 4.4e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:29.827 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 33/1250 epoch 0 eta (0h 17m 24s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.766, mean_iou: 0.382, data: 1.2e-04, track_fwd: 1.7e-01, segfwd: 4.8e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.050 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 34/1250 epoch 0 eta (1h 24m 37s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.782, mean_iou: 0.382, data: 3.3e+00, track_fwd: 1.7e-01, segfwd: 3.9e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.958 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 35/1250 epoch 0 eta (0h 17m 26s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.761, mean_iou: 0.382, data: 1.8e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M `

with setting like https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/experiments/sat/train/sat_res50_davis16.yaml#L110, the metric will be updated for each 100 iters

**Comment by zxyyxzz** [comment]
> 
> 
> You can try to test the dataloader first. whether you can get the train data from the dataloader?

if i

> 
> 
> > > You can try to test the dataloader first. whether you can get the train data from the dataloader?
> > 
> > 
> > I just change the num_process to 1 in config file , is it correct?, i feel confusing ,because i see the miou are all same(miou = 0.382) in every epoch, but the loss keeps dropping:
> > screen shot as following:
> > `rack_fwd: 1.7e-01, segfwd: 3.8e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:35:51.128 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 30/1250 epoch 0 eta (1h 1m 9s) bs: 128 epoch 0, lr: 9.7e-04, multi_bceloss: 0.787, mean_iou: 0.382, data: 2.2e+00, track_fwd: 1.7e-01, segfwd: 4.3e-02, bwd: 1.7e-01, optim: 3.6e-01, max mem: 11955.4M 2020-12-20 09:35:52.020 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 31/1250 epoch 0 eta (0h 17m 10s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.770, mean_iou: 0.382, data: 3.1e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:28.921 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 32/1250 epoch 0 eta (12h 28m 7s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.769, mean_iou: 0.382, data: 3.6e+01, track_fwd: 1.7e-01, segfwd: 4.4e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:29.827 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 33/1250 epoch 0 eta (0h 17m 24s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.766, mean_iou: 0.382, data: 1.2e-04, track_fwd: 1.7e-01, segfwd: 4.8e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.050 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 34/1250 epoch 0 eta (1h 24m 37s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.782, mean_iou: 0.382, data: 3.3e+00, track_fwd: 1.7e-01, segfwd: 3.9e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.958 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 35/1250 epoch 0 eta (0h 17m 26s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.761, mean_iou: 0.382, data: 1.8e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M `
> 
> with setting like
> 
> https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/experiments/sat/train/sat_res50_davis16.yaml#L110
> , the metric will be updated for each 100 iters

yes, i know what you mean, but i just have a single GPU, so i changed the num_process = 1 in config file, is it correct?

**Comment by lzx1413** [comment]
> > You can try to test the dataloader first. whether you can get the train data from the dataloader?
> 
> if i
> 
> > > > You can try to test the dataloader first. whether you can get the train data from the dataloader?
> > > 
> > > 
> > > I just change the num_process to 1 in config file , is it correct?, i feel confusing ,because i see the miou are all same(miou = 0.382) in every epoch, but the loss keeps dropping:
> > > screen shot as following:
> > > `rack_fwd: 1.7e-01, segfwd: 3.8e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:35:51.128 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 30/1250 epoch 0 eta (1h 1m 9s) bs: 128 epoch 0, lr: 9.7e-04, multi_bceloss: 0.787, mean_iou: 0.382, data: 2.2e+00, track_fwd: 1.7e-01, segfwd: 4.3e-02, bwd: 1.7e-01, optim: 3.6e-01, max mem: 11955.4M 2020-12-20 09:35:52.020 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 31/1250 epoch 0 eta (0h 17m 10s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.770, mean_iou: 0.382, data: 3.1e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:28.921 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 32/1250 epoch 0 eta (12h 28m 7s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.769, mean_iou: 0.382, data: 3.6e+01, track_fwd: 1.7e-01, segfwd: 4.4e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:29.827 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 33/1250 epoch 0 eta (0h 17m 24s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.766, mean_iou: 0.382, data: 1.2e-04, track_fwd: 1.7e-01, segfwd: 4.8e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.050 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 34/1250 epoch 0 eta (1h 24m 37s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.782, mean_iou: 0.382, data: 3.3e+00, track_fwd: 1.7e-01, segfwd: 3.9e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.958 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 35/1250 epoch 0 eta (0h 17m 26s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.761, mean_iou: 0.382, data: 1.8e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M `
> > 
> > 
> > with setting like
> > https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/experiments/sat/train/sat_res50_davis16.yaml#L110
> > 
> > , the metric will be updated for each 100 iters
> 
> yes, i know what you mean, but i just have a single GPU, so i changed the num_process = 1 in config file, is it correct?

It's correct,  the num_process controls the number of gpus.

**Comment by zxyyxzz** [comment]
> 
> 
> > > You can try to test the dataloader first. whether you can get the train data from the dataloader?
> > 
> > 
> > if i
> > > > > You can try to test the dataloader first. whether you can get the train data from the dataloader?
> > > > 
> > > > 
> > > > I just change the num_process to 1 in config file , is it correct?, i feel confusing ,because i see the miou are all same(miou = 0.382) in every epoch, but the loss keeps dropping:
> > > > screen shot as following:
> > > > `rack_fwd: 1.7e-01, segfwd: 3.8e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:35:51.128 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 30/1250 epoch 0 eta (1h 1m 9s) bs: 128 epoch 0, lr: 9.7e-04, multi_bceloss: 0.787, mean_iou: 0.382, data: 2.2e+00, track_fwd: 1.7e-01, segfwd: 4.3e-02, bwd: 1.7e-01, optim: 3.6e-01, max mem: 11955.4M 2020-12-20 09:35:52.020 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 31/1250 epoch 0 eta (0h 17m 10s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.770, mean_iou: 0.382, data: 3.1e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:28.921 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 32/1250 epoch 0 eta (12h 28m 7s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.769, mean_iou: 0.382, data: 3.6e+01, track_fwd: 1.7e-01, segfwd: 4.4e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:29.827 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 33/1250 epoch 0 eta (0h 17m 24s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.766, mean_iou: 0.382, data: 1.2e-04, track_fwd: 1.7e-01, segfwd: 4.8e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.050 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 34/1250 epoch 0 eta (1h 24m 37s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.782, mean_iou: 0.382, data: 3.3e+00, track_fwd: 1.7e-01, segfwd: 3.9e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.958 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 35/1250 epoch 0 eta (0h 17m 26s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.761, mean_iou: 0.382, data: 1.8e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M `
> > > 
> > > 
> > > with setting like
> > > https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/experiments/sat/train/sat_res50_davis16.yaml#L110
> > > 
> > > , the metric will be updated for each 100 iters
> > 
> > 
> > yes, i know what you mean, but i just have a single GPU, so i changed the num_process = 1 in config file, is it correct?
> 
> It's correct, the num_process controls the number of gpus.

Thank u

**Comment by zxyyxzz** [comment]
> 
> 
> > > You can try to test the dataloader first. whether you can get the train data from the dataloader?
> > 
> > 
> > if i
> > > > > You can try to test the dataloader first. whether you can get the train data from the dataloader?
> > > > 
> > > > 
> > > > I just change the num_process to 1 in config file , is it correct?, i feel confusing ,because i see the miou are all same(miou = 0.382) in every epoch, but the loss keeps dropping:
> > > > screen shot as following:
> > > > `rack_fwd: 1.7e-01, segfwd: 3.8e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:35:51.128 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 30/1250 epoch 0 eta (1h 1m 9s) bs: 128 epoch 0, lr: 9.7e-04, multi_bceloss: 0.787, mean_iou: 0.382, data: 2.2e+00, track_fwd: 1.7e-01, segfwd: 4.3e-02, bwd: 1.7e-01, optim: 3.6e-01, max mem: 11955.4M 2020-12-20 09:35:52.020 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 31/1250 epoch 0 eta (0h 17m 10s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.770, mean_iou: 0.382, data: 3.1e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:28.921 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 32/1250 epoch 0 eta (12h 28m 7s) bs: 128 epoch 0, lr: 1.0e-03, multi_bceloss: 0.769, mean_iou: 0.382, data: 3.6e+01, track_fwd: 1.7e-01, segfwd: 4.4e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:29.827 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 33/1250 epoch 0 eta (0h 17m 24s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.766, mean_iou: 0.382, data: 1.2e-04, track_fwd: 1.7e-01, segfwd: 4.8e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.050 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 34/1250 epoch 0 eta (1h 24m 37s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.782, mean_iou: 0.382, data: 3.3e+00, track_fwd: 1.7e-01, segfwd: 3.9e-02, bwd: 1.5e-01, optim: 3.8e-01, max mem: 11955.4M 2020-12-20 09:36:34.958 | INFO | videoanalyst.engine.trainer.trainer_impl.distributed_sat_trainer:train:131 - 35/1250 epoch 0 eta (0h 17m 26s) bs: 128 epoch 0, lr: 1.1e-03, multi_bceloss: 0.761, mean_iou: 0.382, data: 1.8e-04, track_fwd: 1.7e-01, segfwd: 4.9e-02, bwd: 1.4e-01, optim: 3.8e-01, max mem: 11955.4M `
> > > 
> > > 
> > > with setting like
> > > https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/experiments/sat/train/sat_res50_davis16.yaml#L110
> > > 
> > > , the metric will be updated for each 100 iters
> > 
> > 
> > yes, i know what you mean, but i just have a single GPU, so i changed the num_process = 1 in config file, is it correct?
> 
> It's correct, the num_process controls the number of gpus.

Hi,  i changed my computer(server) to train VOS, the new server has two Titan xp GPUS,  when i want to train it , but get stuck,  it stuck here for a long time , and no other information appeared:
screen-shot as following:
`2020-12-21 19:50:08.300 | INFO     | videoanalyst.data.dataset.dataset_impl.ytb_vos:_ensure_cache:86 - YoutubeVOSDataset: loaded cache file /DATACENTER/1/zxy/datasets/youtubevos/cache/train.pkl
2020-12-21 19:50:08.301 | INFO     | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: COCODataset, length 122218
2020-12-21 19:50:08.302 | INFO     | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: DavisDataset, length 145
2020-12-21 19:50:08.303 | INFO     | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: YoutubeVOSDataset, length 6459
2020-12-21 19:50:08.304 | INFO     | videoanalyst.data.adaptor_dataset:__getitem__:48 - AdaptorDataset #0 built datapipeline with seed=100087
2020-12-21 19:50:11.400 | INFO     | videoanalyst.data.builder:build:46 - Dummy AdaptorDataset destroyed.
2020-12-21 19:50:11.402 | INFO     | videoanalyst.data.builder:build:50 - Build real AdaptorDataset
2020-12-21 19:50:11.403 | INFO     | videoanalyst.utils.misc:__exit__:102 - Dummy dataloader building elapsed time: 18.144057
2020-12-21 19:50:11.403 | INFO     | __main__:<module>:180 - Dummy dataloader destroyed.
2020-12-21 19:50:11.979 | INFO     | videoanalyst.model.module_base:update_params:62 - Load pretrained SiamTrack parameters from: models/siamfcpp/siamfcpp-alexnet-vot-md5_18fd31a2f94b0296c08fff9b0f9ad240.pkl whose md5sum is 18fd31a2f94b0296c08fff9b0f9ad240
2020-12-21 19:50:12.820 | INFO     | videoanalyst.model.module_base:update_params:62 - Load pretrained ResNet50_M parameters from: models/resnet/res-50-imagenet-fff49.pkl whose md5sum is 170b1ae0b972728af3b05837733fff49
2020-12-21 19:50:13.696 | INFO     | videoanalyst.model.module_base:update_params:62 - Load pretrained ResNet50_M parameters from: models/resnet/res-50-imagenet-fff49.pkl whose md5sum is 170b1ae0b972728af3b05837733fff49
`
Do you know what happened about it?

**Comment by zxyyxzz** [comment]
sometime it stuck in :
`2020-12-21 20:29:53.943 | INFO     | videoanalyst.data.adaptor_dataset:__getitem__:48 - AdaptorDataset #1988477 built datapipeline with seed=196825
2020-12-21 20:29:54.050 | INFO     | videoanalyst.data.dataset.dataset_impl.coco:_ensure_cache:125 - COCODataset: loaded cache file /DATACENTER/1/zxy/datasets/coco/cache/coco_mask_val2017.pkl
2020-12-21 20:29:54.057 | INFO     | videoanalyst.data.dataset.dataset_impl.davis:_ensure_cache:91 - DavisDataset: loaded cache file /DATACENTER/1/zxy/datasets/DAVIS/cache/train2017.pkl
2020-12-21 20:29:54.251 | INFO     | videoanalyst.data.dataset.dataset_impl.ytb_vos:_ensure_cache:86 - YoutubeVOSDataset: loaded cache file /DATACENTER/1/zxy/datasets/youtubevos/cache/train.pkl
2020-12-21 20:29:54.252 | INFO     | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: COCODataset, length 122218
2020-12-21 20:29:54.252 | INFO     | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: DavisDataset, length 145
2020-12-21 20:29:54.252 | INFO     | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: YoutubeVOSDataset, length 6459
2020-12-21 20:29:54.253 | INFO     | videoanalyst.data.adaptor_dataset:__getitem__:48 - AdaptorDataset #3040009 built datapipeline with seed=845984
`

**Comment by lzx1413** [comment]
> sometime it stuck in :
> `2020-12-21 20:29:53.943 | INFO | videoanalyst.data.adaptor_dataset:__getitem__:48 - AdaptorDataset #1988477 built datapipeline with seed=196825 2020-12-21 20:29:54.050 | INFO | videoanalyst.data.dataset.dataset_impl.coco:_ensure_cache:125 - COCODataset: loaded cache file /DATACENTER/1/zxy/datasets/coco/cache/coco_mask_val2017.pkl 2020-12-21 20:29:54.057 | INFO | videoanalyst.data.dataset.dataset_impl.davis:_ensure_cache:91 - DavisDataset: loaded cache file /DATACENTER/1/zxy/datasets/DAVIS/cache/train2017.pkl 2020-12-21 20:29:54.251 | INFO | videoanalyst.data.dataset.dataset_impl.ytb_vos:_ensure_cache:86 - YoutubeVOSDataset: loaded cache file /DATACENTER/1/zxy/datasets/youtubevos/cache/train.pkl 2020-12-21 20:29:54.252 | INFO | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: COCODataset, length 122218 2020-12-21 20:29:54.252 | INFO | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: DavisDataset, length 145 2020-12-21 20:29:54.252 | INFO | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: YoutubeVOSDataset, length 6459 2020-12-21 20:29:54.253 | INFO | videoanalyst.data.adaptor_dataset:__getitem__:48 - AdaptorDataset #3040009 built datapipeline with seed=845984 `

Does the machine have enough memory to load the whole training dataset?

**Comment by zxyyxzz** [comment]
> 
> 
> > sometime it stuck in :
> > `2020-12-21 20:29:53.943 | INFO | videoanalyst.data.adaptor_dataset:__getitem__:48 - AdaptorDataset #1988477 built datapipeline with seed=196825 2020-12-21 20:29:54.050 | INFO | videoanalyst.data.dataset.dataset_impl.coco:_ensure_cache:125 - COCODataset: loaded cache file /DATACENTER/1/zxy/datasets/coco/cache/coco_mask_val2017.pkl 2020-12-21 20:29:54.057 | INFO | videoanalyst.data.dataset.dataset_impl.davis:_ensure_cache:91 - DavisDataset: loaded cache file /DATACENTER/1/zxy/datasets/DAVIS/cache/train2017.pkl 2020-12-21 20:29:54.251 | INFO | videoanalyst.data.dataset.dataset_impl.ytb_vos:_ensure_cache:86 - YoutubeVOSDataset: loaded cache file /DATACENTER/1/zxy/datasets/youtubevos/cache/train.pkl 2020-12-21 20:29:54.252 | INFO | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: COCODataset, length 122218 2020-12-21 20:29:54.252 | INFO | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: DavisDataset, length 145 2020-12-21 20:29:54.252 | INFO | videoanalyst.data.sampler.sampler_base:__init__:52 - Sampler's underlying datasets: YoutubeVOSDataset, length 6459 2020-12-21 20:29:54.253 | INFO | videoanalyst.data.adaptor_dataset:__getitem__:48 - AdaptorDataset #3040009 built datapipeline with seed=845984 `
> 
> Does the machine have enough memory to load the whole training dataset?

Thank u, i'll check it, now i use another machine.

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.
