### ISSUE TITLE
siamfcpp's result is strange

### ISSUE THREAD

**Issue by lfxx** [MegviiDetection/video_analyst#167]
I use black.png　as template,every frame which has this template get score 0.6.But those frames which do not have this template select animal.png as target get score 0.6 as well.This really strange.black.png and animal.png is totally different.Should not get such high value 0.6.Please help me out
![black](https://user-images.githubusercontent.com/27956643/103059720-e6141a00-45e0-11eb-8849-fb607697181a.png)
black.png
![animal](https://user-images.githubusercontent.com/27956643/103059966-a0a41c80-45e1-11eb-9b4e-651fa8e5ede3.png)
animal.png

**Comment by lzx1413** [comment]
The pipeline will pad the search image with zero if the target's size is as big as the whole image, You can view the actual data fed into the network to confirm the real input image data to generate the features.

**Comment by lfxx** [comment]
> The pipeline will pad the search image with zero if the target's size is as big as the whole image, You can view the actual data fed into the network to confirm the real input image data to generate the features.

Thanks for your kindly reply.Another question is even if there is no template object,model will still give a target,why?
谢谢您的回复．我发现我选定目标后，比如说一个人，在后续视频帧中，即使没有这个人，网络也会给出一个bbox去圈选其他目标,正常不应该是没有bbox输出才对吗？或者说怎么判断目标丢失这种情况呢

**Comment by lzx1413** [comment]
可以在pipeline中设定打分阈值，低于打分阈值就不输出结果，并且在后面开始全图搜索目标，具体的pipeline可以参考 https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py, short-term sot里面是假设物体不会消失的， 考虑消失的情景需要额外加点逻辑， 很多long-term的方法就是这样做的

**Comment by lfxx** [comment]
> 可以在pipeline中设定打分阈值，低于打分阈值就不输出结果，并且在后面开始全图搜索目标，具体的pipeline可以参考 [`caa9791`/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py](https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py), short-term sot里面是假设物体不会消失的， 考虑消失的情景需要额外加点逻辑， 很多long-term的方法就是这样做的

Thanks for your specific explanation,very useful.Want to know if segementation in sat is salient object segementation or cls limited segementation.
感谢您的详细解答,很有用．想知道SAT中的语义分割是显著性分割吗还是限定目标类别的分割

**Comment by lzx1413** [comment]
> > 可以在pipeline中设定打分阈值，低于打分阈值就不输出结果，并且在后面开始全图搜索目标，具体的pipeline可以参考 [`caa9791`/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py](https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py), short-term sot里面是假设物体不会消失的， 考虑消失的情景需要额外加点逻辑， 很多long-term的方法就是这样做的
> 
> Thanks for your specific explanation,very useful.Want to know if segementation in sat is salient object segementation or cls limited segementation.
> 感谢您的详细解答,很有用．想知道SAT中的语义分割是显著性分割吗还是限定目标类别的分割

和sot一样，根据模板的目标来跟踪分割，提供的目标用mask而不是用框，demo可以参考https://github.com/MegviiDetection/video_analyst/blob/master/demo/main/video/sat_video.py

**Comment by lfxx** [comment]
> > > 可以在pipeline中设定打分阈值，低于打分阈值就不输出结果，并且在后面开始全图搜索目标，具体的pipeline可以参考 [`caa9791`/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py](https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py), short-term sot里面是假设物体不会消失的， 考虑消失的情景需要额外加点逻辑， 很多long-term的方法就是这样做的
> > 
> > 
> > Thanks for your specific explanation,very useful.Want to know if segementation in sat is salient object segementation or cls limited segementation.
> > 感谢您的详细解答,很有用．想知道SAT中的语义分割是显著性分割吗还是限定目标类别的分割
> 
> 和sot一样，根据模板的目标来跟踪分割，提供的目标用mask而不是用框，demo可以参考[https://github.com/MegviiDetection/video_analyst/blob/master/demo/main/video/sat_video.py](https://github.com/MegviiDetection/video_analyst/blob/master/demo/main/video/sat_video.py?rgh-link-date=2020-12-24T09%3A47%3A22Z)

Thanks for your quickly reply.I will look on it

**Comment by lfxx** [comment]
> > > 可以在pipeline中设定打分阈值，低于打分阈值就不输出结果，并且在后面开始全图搜索目标，具体的pipeline可以参考 [`caa9791`/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py](https://github.com/MegviiDetection/video_analyst/blob/caa97911efada58941b1629fd74a1b1ce1a76659/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py), short-term sot里面是假设物体不会消失的， 考虑消失的情景需要额外加点逻辑， 很多long-term的方法就是这样做的
> > 
> > 
> > Thanks for your specific explanation,very useful.Want to know if segementation in sat is salient object segementation or cls limited segementation.
> > 感谢您的详细解答,很有用．想知道SAT中的语义分割是显著性分割吗还是限定目标类别的分割
> 
> 和sot一样，根据模板的目标来跟踪分割，提供的目标用mask而不是用框，demo可以参考[https://github.com/MegviiDetection/video_analyst/blob/master/demo/main/video/sat_video.py](https://github.com/MegviiDetection/video_analyst/blob/master/demo/main/video/sat_video.py?rgh-link-date=2020-12-24T09%3A47%3A22Z)

已经测试了，感觉效果很不错．想请教您一个题外话，sat给出的mask有时候不全，有什么办法将其补全吗，我能想到opencv的漫水填充，但是实际测试了下效果不是很好

**Comment by lzx1413** [comment]
如果形态变化较大的话，只根据首帧信息可能确实分割不全，如果目标类别固定的话，建议上一个检测器+分割的模型，可能会好一点

**Comment by lfxx** [comment]
> 如果形态变化较大的话，只根据首帧信息可能确实分割不全，如果目标类别固定的话，建议上一个检测器+分割的模型，可能会好一点

好的，谢谢大佬指点
