### ISSUE TITLE
Can you tell me what the first pre-training model does?

### ISSUE THREAD

**Issue by zh-mi** [MegviiDetection/video_analyst#170]
![image](https://user-images.githubusercontent.com/55775401/103145372-530be900-4774-11eb-8d5a-b83a783dfe46.png)
在测试代码的backbone下的预训练模型有什么作用？？是直接空着吗？？

**Comment by zh-mi** [comment]
images不能用，我的问题如下：
test:
  track:
    exp_name: &TEST_NAME "siamfcpp_alexnet"
    exp_save: &TEST_SAVE "logs"
    model:
      backbone:
        name: "AlexNet"
        AlexNet:
          pretrain_model_path: ""
      losses:
        names: []
      task_head:
        name: "DenseboxHead"
        DenseboxHead:
          total_stride: 8
          score_size: &SCORE_SIZE_TEST 17
          x_size: &X_SIZE_TEST 303
          num_conv3x3: &NUM_CONV3x3 3
          head_conv_bn: [False, False, True]
      task_model:
        name: "SiamTrack"
        SiamTrack:
          pretrain_model_path: "models/siamfcpp/siamfcpp-alexnet-vot-md5_88e4e9ee476545b952b04a
、

backbone:
        name: "AlexNet"
        AlexNet:
          pretrain_model_path: ""
这个test代码的backbone下的预训练模型有什么作用吗？？还是空着？

**Comment by lzx1413** [comment]
test时候直接设置模型权重就好了，backbone的可以空着
