### ISSUE TITLE
SAT's output's edge is a little fuzzy

### ISSUE THREAD

**Issue by lfxx** [MegviiDetection/video_analyst#171]
SAT's output mask's edge is a little fuzzy,any suggestions on sharping edge?
SAT输出的mask边界不是很准确，比较粗糙，有什么办法可以优化这种情况吗
I find a repo named cascadepsp on github can do this,but it is too slow.

**Comment by lzx1413** [comment]
你可以试试CRF等后处理方法做精细化mask

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.
