### ISSUE TITLE
siamfcpp start loading subset train Error

### ISSUE THREAD

**Issue by zh-mi** [MegviiDetection/video_analyst#172]
![image](https://user-images.githubusercontent.com/55775401/103255113-0c5ffe00-49c3-11eb-8ccb-d18ff27ca726.png)
我在导入训练数据的时候  老是报这个assert len(img_files) == len(anno)错误，这是数据集有问题吗，并且有时候在运行python3 ./main/train.py ，每次出现错误的文件都不同，但是都集中早5956-5968之间。这是怎么回事，有大佬能帮忙解惑吗？

**Comment by lzx1413** [comment]
可能你下载的数据集不完整？ 可以 输出一下错误的视频序列是不是真的图像和标注数目不匹配吧

**Comment by zh-mi** [comment]
我数据集在官网上下载的，应该没有问题，每运行一次 python3 ./main/train.py --config 'experiments/siamfcpp/train/got10k/siamfcpp_alexnet-trn.yaml'，进度条显示出现错误的文件都不一样，
![image](https://user-images.githubusercontent.com/55775401/103256022-9c537700-49c6-11eb-9cce-0bef92056b03.png)
![image](https://user-images.githubusercontent.com/55775401/103256057-b68d5500-49c6-11eb-8570-146534523a13.png)
![image](https://user-images.githubusercontent.com/55775401/103256065-c2791700-49c6-11eb-87c2-e4eed53394ed.png)

**Comment by zh-mi** [comment]
我先试试将这两个数据打印出来吧

**Comment by zh-mi** [comment]
谢谢您的解答，打印出来的结果确实不一样，原因是数据集有部分损坏了
