### ISSUE TITLE
estimation quality assessment branch（SOT）

### ISSUE THREAD

**Issue by nxbs** [MegviiDetection/video_analyst#173]
![iou](https://user-images.githubusercontent.com/48122591/103257813-b8a6e200-49cd-11eb-868f-2642ee67b0d1.png)
Hello, could you tell me how is the ground-truth of the IoU experiment in the quality assessment branch calculated?  The ground-truth bounding box B*  and the corresponding location of B on the input image  are known, but how to determine the width and height of the predicted bounding box B

**Comment by lzx1413** [comment]
The output contains the bounding box of the target, which including the width and height

**Comment by nxbs** [comment]
> The output contains the bounding box of the target, which including the width and height

Do you mean using the output of the regression branch?

**Comment by lzx1413** [comment]
> > The output contains the bounding box of the target, which including the width and height
> 
> Do you mean using the output of the regression branch?

Yes, that is right
