### ISSUE TITLE
siamfcpp one 1080Ti run python3 ./main/train.py --config experiments/siamfcpp/train/siamfcpp_alexnet-trn.yaml,but it is very slow

### ISSUE THREAD

**Issue by zh-mi** [MegviiDetection/video_analyst#174]
![image](https://user-images.githubusercontent.com/55775401/103282203-004e5d80-4a10-11eb-9320-c8037f1572b7.png)
我用一张1080ti跑siamfcpp/train/siamfcpp_alexnet-trn.yaml，源码设置的参数我都没改动，GPU的利用率时高时低，大部分的时间利用率为0，按照时间来算一个epoch需要20多个小时，这是啥原因呢？

**Comment by zh-mi** [comment]
![image](https://user-images.githubusercontent.com/55775401/103282391-997d7400-4a10-11eb-836c-73fde98e9c35.png)
这是第一个批次运行时的情况

**Comment by cuikf** [comment]
您好，打扰您了，我也有同样的问题，GPU利用率时高时低，请问您解决了吗？

**Comment by MARMOTatZJU** [comment]
@cuikf  @zh-mi  这种情况通常是 batch size 可能对于机器来说过大了，数据供应成了门槛。建议把 batch-size 调小。

**Comment by cuikf** [comment]
好的，谢谢！

**Comment by zh-mi** [comment]
谢谢@MARMOTatZJU
