### ISSUE TITLE
Problem about online classifier.

### ISSUE THREAD

**Issue by kuailedagongzai** [MegviiDetection/video_analyst#175]
Well, i am learning the online classifier part of the siamfcpp ,but i can not find a paper discribe similar structure.Could you please give me some advice on the structure about the online classifier?

**Comment by lzx1413** [comment]
the online version of siamfcpp is the combination of siamfc++ and ATOM, there is no paper to illustrate it. You can refer to DROL for some suggestions.

**Comment by kuailedagongzai** [comment]
Thanks a lot！This repo is a great resource for learning!
