### ISSUE TITLE
 How does this warning about siamfcpp go away?

### ISSUE THREAD

**Issue by zh-mi** [MegviiDetection/video_analyst#176]
![image](https://user-images.githubusercontent.com/55775401/103351916-ab7a1800-4adf-11eb-89de-232a20c3384d.png)
这个警告是咋回事啊？？大佬指点一下咋消除

**Comment by zh-mi** [comment]
这个是预训练模型本身的问题吗，我用的是官网提供的模型

**Comment by lzx1413** [comment]
torch官网的alexnet？，我们的alexnet是有bn层的

**Comment by MARMOTatZJU** [comment]
@zh-mi 由于这个主干网络的参数为内部框架转换而来，由于不同框架间bn的底层实现不一致并且细节复杂，导致对齐有难度，参数在不同框架之间不具有意义，因此没有转换。bn将会在跟踪器训练时重新学习&统计。

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.

**Comment by ghost** [comment]
请问我下载的就是作者提供的预训练模型也出现了这种错如何解决呢
