### ISSUE TITLE
Where can we find the raw results of siamfc++?

### ISSUE THREAD

**Issue by sysu-shey** [MegviiDetection/video_analyst#178]
Hi！Where can we find the tracking results of siamfc++? @MARMOTatZJU

**Comment by lzx1413** [comment]
Please refer to https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/SOT_MODEL_ZOO.md

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.
