### ISSUE TITLE
Separate trace and split

### ISSUE THREAD

**Issue by dingguodong-826** [MegviiDetection/video_analyst#180]
Hello, thank you very much for the work done by you and your team. I would like to improve the network on the basis of your team. I would like to ask you some questions, could you add the contact information: WeChat or QQ

**Comment by lzx1413** [comment]
Thank you for your attention to our work and  my wechat is lzx1413

**Comment by MARMOTatZJU** [comment]
@dingguodong-826 Yes, feel free to check me out on Linkedin (where I post my contact on WeChat).

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.
