### ISSUE TITLE
loss weight

### ISSUE THREAD

**Issue by LPXTT** [MegviiDetection/video_analyst#181]
Hi, 
In the code, the weights of the three losses (cls, centerness and iou) are 1.0, 1.0, 3.0, right?
How do you set them?  I trained the model and found the final cls, centerness and iou loss are about 0.09, 0.02 and 0.22. The IOU loss is bigger than the other two losses. The IOU weight is also bigger than those of the two losses. It is a little wired.
Thank you for your help~

**Comment by MARMOTatZJU** [comment]
@LPXTT This kind of divergence in final training loss seems to be normal for a multi-task training model (like SiamFC++).

The weights were set empirically. We just found that larger weight for regressor leads to better test result on benchmarks in general.

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.
