### ISSUE TITLE
torch 版本为 1.8.0， torchision 版本为 0.9.0， 在对 webcam 进行 sot测试时，按下s拖动鼠标选取目标框后报错

### ISSUE THREAD

**Issue by ShiAngWang** [MegviiDetection/video_analyst#183]
torch 版本为 1.8.0， torchvision 版本为 0.9.0， 在对 webcam 进行 sot测试时，按下s拖动鼠标选取目标框后报错，报错如图
![Screenshot_20210306_000222](https://user-images.githubusercontent.com/26656883/110140658-490b0400-7e0f-11eb-90e2-cab07756b3a3.png)

在卸载并重装 torch 1.7.1   torchvision 0.8.2 后正常运行
想问下您那是否能复现这个问题，以及是否有什么可行的解决方法

**Comment by MARMOTatZJU** [comment]
目前我没有可以运行的环境。但是搜索了一下，先考虑确认一下cuda和cudnn版本是否和pytorch 1.8.0匹配。

**Comment by ShiAngWang** [comment]
@MARMOTatZJU 您好，我这边检查并重新安装了下 cuda 10.2，cudnn 7.65 和 cuda 11.1，cudnn 8.1.1,
这两种情况下，使用 torch 1.7.1 可以正常运行
使用 torch 1.8.0 都不可以正常运行，和上述报错情况一致

**Comment by MARMOTatZJU** [comment]
> @MARMOTatZJU 您好，我这边检查并重新安装了下 cuda 10.2，cudnn 7.65 和 cuda 11.1，cudnn 8.1.1,
> 这两种情况下，使用 torch 1.7.1 可以正常运行
> 使用 torch 1.8.0 都不可以正常运行，和上述报错情况一致

torchvision版本和torch匹配吗？

**Comment by ShiAngWang** [comment]
> > @MARMOTatZJU 您好，我这边检查并重新安装了下 cuda 10.2，cudnn 7.65 和 cuda 11.1，cudnn 8.1.1,
> > 这两种情况下，使用 torch 1.7.1 可以正常运行
> > 使用 torch 1.8.0 都不可以正常运行，和上述报错情况一致
> 
> torchvision版本和torch匹配吗？

是匹配的，torch 1.8.0 torchvision 0.9.0 时运行出问题，但是版本匹配

**Comment by lzx1413** [comment]
https://github.com/pytorch/pytorch/issues/53458 感觉是torch 1.8还有些问题，建议先用1.7.1及以下版本吧

**Comment by ShiAngWang** [comment]
好的

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion happened. Feel free to reopen it.
