### ISSUE TITLE
How to train and test on youtubeVos2019?

### ISSUE THREAD

**Issue by sunsiyang2015** [MegviiDetection/video_analyst#184]
hello, it is excellent work.
I want to know how to train and evaluate on youtubeVos2019?

**Comment by lzx1413** [comment]
we have implemented the dataset for youtubevos 2018 at https://github.com/MegviiDetection/video_analyst/blob/master/videoanalyst/data/dataset/dataset_impl/ytb_vos.py. You can try to edit it to load youtubevos 2019. For evaluation, you can refer to the davis tester https://github.com/MegviiDetection/video_analyst/blob/master/videoanalyst/engine/tester/tester_impl/davis.py to generate the results which is needed for the server https://competitions.codalab.org/competitions/20127#participate

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
