### ISSUE TITLE
target feature( self._state['features']  in code or Template image in paper) never update  during the whole tracking time?

### ISSUE THREAD

**Issue by xiexie123** [MegviiDetection/video_analyst#185]
hi guys,
    great work and thanks for the code.
     I read the paper and code, and notice that target feature( self._state['features']  in code or Template image in paper) never update  during the whole tracking time? did I miss something? because in some case, the object appearance (feature) changes.

**Comment by MARMOTatZJU** [comment]
@xiexie123 Your observation is right. As you mentioned, we didn't delve into the topic of model updating in our work (for this topic you can refer to papers such as  LTMU from Prof. Dong Wang's group), and the template of a typical SiamFC++ change does not update during tracking.

During training, the tracker model is fed with different pair of template & search samples whose appearance changes over time, and thus gain the ability to deal with appearance change even with a static template.

However, some heuristics are feasible to achieve this, such as doing an EMA over the template.

**Comment by xiexie123** [comment]
> @xiexie123 Your observation is right. As you mentioned, we didn't delve into the topic of model updating in our work (for this topic you can refer to papers such as LTMU from Prof. Dong Wang's group), and the template of a typical SiamFC++ change does not update during tracking.
> 
> During training, the tracker model is fed with different pair of template & search samples whose appearance changes over time, and thus gain the ability to deal with appearance change even with a static template.
> 
> However, some heuristics are feasible to achieve this, such as doing an EMA over the template.

ok I see, Thanks for your quick reply.

**Comment by MARMOTatZJU** [comment]
Closed as replied. Feel free to reopen.
