### ISSUE TITLE
TEST ERROR

### ISSUE THREAD

**Issue by yangxiaoyany** [MegviiDetection/video_analyst#186]
Hello,when I use the following  order to view the performance.json, it can show a picture named figure1 , but it cant draw curves.Can you help me to deal with it.Thank you very much

**view logs/GOT-Benchmark/report/UAV123/siamfcpp_alexnet/performance.json**

**Comment by lzx1413** [comment]
Hello, What's the real order of **view**. It seems that we don't supply this function.

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
