### ISSUE TITLE
why the feature adjustment for x(search) and z(template) are different

### ISSUE THREAD

**Issue by xiexie123** [MegviiDetection/video_analyst#190]
https://github.com/MegviiDetection/video_analyst/blob/f4d1bccb1c698961fed3cb70808f1177fab13bdd/videoanalyst/model/task_model/taskmodel_impl/siamese_track.py#L217

Obviously, there two independent feature adjustment (self.r_z_k and self.r_x), while the description in paper is 

> The siamese backbone, which shares parameters between two branches, performs the same transform on the input z and x to embed them into a common feature space for subsequent tasks

and according to equation (1) in paper, seems the feature adjustment(Ψ) is shared. 

Is there any reason or any experiment to discuss whether or not to share Ψ.

**Comment by lzx1413** [comment]
According to our experiments, the AO of  got-10 will be lower slightly (69.5 vs 72) while keeping them sharing the weights.

**Comment by MARMOTatZJU** [comment]
@xiexie123 Generally speaking, performance shall be always get higher if you make more parameters unshared. This current design of SotA should be some trade-off between performance and memory consumption.

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
