### ISSUE TITLE
The recommend target template size used by sot

### ISSUE THREAD

**Issue by lfxx** [MegviiDetection/video_analyst#191]
I find that if the size of target template is small,such as 150*150,the sot get poor performance.I would like to know what target template size is proper for sot?

**Comment by lzx1413** [comment]
SOT needs the rich feature representation of the target for tracking, and the template image will be resized to 128*128 in the pipeline. However, the appropriate raw input size depends on your target itself.

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
