### ISSUE TITLE
why dose cv2.warpAffine can do crop in your code?

### ISSUE THREAD

**Issue by zxyyxzz** [MegviiDetection/video_analyst#192]
@lzx1413 
Hi：
   I just read your source code,  but i found a confusing place in your code as following:

   `    crop_cxywh = np.concatenate(
        [np.array(pos), np.array((original_sz, original_sz))], axis=-1)

    crop_xyxy = cxywh2xyxy(crop_cxywh)

    # warpAffine transform matrix

    M_13 = crop_xyxy[0]

    M_23 = crop_xyxy[1]

    M_11 = (crop_xyxy[2] - M_13) / (model_sz - 1)

    M_22 = (crop_xyxy[3] - M_23) / (model_sz - 1)

    mat2x3 = np.array([
        M_11,
        0,
        M_13,
        0,
        M_22,
        M_23,
    ]).reshape(2, 3)
    im_patch = cv2.warpAffine(im,
                              mat2x3, (model_sz, model_sz),
                              flags=(cv2.INTER_LINEAR | cv2.WARP_INVERSE_MAP),
                              borderMode=cv2.BORDER_CONSTANT,
                              borderValue=tuple(map(int, avg_chans)))`

**Comment by zxyyxzz** [comment]
您好，我感觉英文可能不能很清楚表达我的想法，我就用中文叙述了：
我思考了2天，实在想不通为什么可以做裁剪，您取了Bouding box左上角的坐标作为仿射变换矩阵中的平移量，可是这个平移只能使得图片往右下角移动，请问他怎么可以裁剪出想要的感兴趣区域呢？
希望能够得到您的回复！谢谢~

**Comment by MARMOTatZJU** [comment]
@zxyyxzz 
warpAffine的方向是`cv2.WARP_INVERSE_MAP`，相当于是dst_img的点坐标映射到src_img的点坐标。

**Comment by zxyyxzz** [comment]
> @zxyyxzz
> warpAffine的方向是`cv2.WARP_INVERSE_MAP`，相当于是dst_img的点坐标映射到src_img的点坐标。
谢谢您的回复！~
cv2.WARP_INVERSE_MAP的公式应该是：**dst(x,y) = src(M11*x+M12*Y+M13, M21*x+M22*y+M23)**
其中，M13和M23分别是左上角的x,y坐标，按照公式的理解应该是src_img向右和向下平移了M13和M23的距离，怎么就变成是裁剪了呢？

**Comment by lzx1413** [comment]
@zxyyxzz  因为输出尺寸是确定的model_sz， 反向查询位置也就只会查询对应的crop出来的部分了

**Comment by zxyyxzz** [comment]
> > @zxyyxzz
> > warpAffine的方向是`cv2.WARP_INVERSE_MAP`，相当于是dst_img的点坐标映射到src_img的点坐标。
> > 谢谢您的回复！~
> > cv2.WARP_INVERSE_MAP的公式应该是：**dst(x,y) = src(M11_x+M12_Y+M13, M21_x+M22_y+M23)**
> > 其中，M13和M23分别是左上角的x,y坐标，按照公式的理解应该是src_img向右和向下平移了M13和M23的距离，怎么就变成是裁剪了呢？



> @zxyyxzz 因为输出尺寸是确定的model_sz， 反向查询位置也就只会查询对应的crop出来的部分了，这里用warpaffine是用来做resize和crop两个工作的

我今天自己推了一下，cv2.WARP_INVERSE_MAP就是求变换矩阵M的逆，大概知道是怎么回事了，非常感谢！~

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
