### ISSUE TITLE
 The engine plan file is generated on an incompatible device, expecting compute 6.1 got compute 7.5, please rebuild.

### ISSUE THREAD

**Issue by lfxx** [MegviiDetection/video_analyst#194]
Use repo's trt model on Tesla P4 leads to the error above,what should i do?Thanks!

**Comment by lzx1413** [comment]
You can dump the trt model on your P4 device by yourself(https://github.com/MegviiDetection/video_analyst/blob/master/main/cvt_trt.py).  The trt model is related to the devices.

**Comment by lfxx** [comment]
Solved.Thanks!
