### ISSUE TITLE
SAT segmentor模型下载的百度云链接失效了

### ISSUE THREAD

**Issue by zzg-zzg** [MegviiDetection/video_analyst#197]
[https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/VOS_SETUP.md](https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/VOS_SETUP.md)中给出的百度云链接失效了，可以的话麻烦更新一下

**Comment by lzx1413** [comment]
链接: https://pan.baidu.com/s/14Ng6RO0V1bAzdZWkrefHBg 提取码: q4mr 复制这段内容后打开百度网盘手机App，操作更方便哦
you can try this link

**Comment by zzg-zzg** [comment]
Thanks！
