### ISSUE TITLE
Can you tell me what these four documents mean?

### ISSUE THREAD

**Issue by zh-mi** [MegviiDetection/video_analyst#198]
![image](https://user-images.githubusercontent.com/55775401/118206351-e67c5700-b494-11eb-96bd-5fb40756850b.png)
![image](https://user-images.githubusercontent.com/55775401/118206396-014ecb80-b495-11eb-9e12-d25caa7fc1f3.png)
我注释的四个对吗？还有多模板跟踪就是多目标跟踪吗？我们现在下面这个.yaml调用的是哪一个跟踪器呢？？
![image](https://user-images.githubusercontent.com/55775401/118206645-84702180-b495-11eb-8306-05265a14ab7e.png)

**Comment by lzx1413** [comment]
lt是长时跟踪， online是带在线优化的短时跟踪，osdet可以认为是个检测器，multi_temp是多模板优化的短时跟踪， 调用的tracke版本可以在配置文件中查看到
