### ISSUE TITLE
How  to fine-tune SAT on a new dataset

### ISSUE THREAD

**Issue by zzg-zzg** [MegviiDetection/video_analyst#199]
Thank you for your wonderful work,
I tested the SAT on my own dataset but the results were not good enough.
I guess it might be because my target category is not very common.
I decided to fine-tune the pre-trained model on my dataset.
What files and configurations do I need to modify? How to deal with the dataset(about the format)?

**Comment by lzx1413** [comment]
The format of dataset is defined here https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/VOS_SETUP.md, we did not format the dataset to the same schema, so you can find the dataset  class here https://github.com/MegviiDetection/video_analyst/blob/master/videoanalyst/data/dataset/dataset_impl/davis.py  and the config files lie in https://github.com/MegviiDetection/video_analyst/tree/master/experiments/sat/train

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
