### ISSUE TITLE
SiamfcppOnlineTrackPipeline

### ISSUE THREAD

**Issue by oliver8459** [MegviiDetection/video_analyst#200]
i didn't understand the code, i read the paper, is it ATOM? or your own method?
and i didn't see any template updated, what the 'online' mean?

**Comment by lzx1413** [comment]
https://github.com/MegviiDetection/video_analyst/blob/f4d1bccb1c698961fed3cb70808f1177fab13bdd/videoanalyst/pipeline/tracker_impl/siamfcpp_online_track.py#L442
we adopt online classification from ATOM.

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
