### ISSUE TITLE
Could you release the code tools/test/test_DAVIS2017.sh ?

### ISSUE THREAD

**Issue by zhouweii234** [MegviiDetection/video_analyst#201]
I want to train SAT and test it on DAVIS2017, DAVIS2016 and YouTube-VOS, could you release the test code ?

**Comment by lzx1413** [comment]
python3 ./main/test.py --config 'experiments/sat/test/sat_res50-davis17.yaml
python3 ./main/test.py --config 'experiments/sat/test/sat_res50-davis17.yaml

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
