### ISSUE TITLE
I encountered a problem when running the demo with extracted image files. Can you help me solve the following problems?

### ISSUE THREAD

**Issue by long-wa** [MegviiDetection/video_analyst#214]
hi, I encountered a problem when running the demo with extracted image files. Can you help me solve the following problems?
""python3 ./demo/main/video/sot_video.py --config 'experiments/siamfcpp/test/vot/siamfcpp_alexnet.yaml' --device cuda --video datasets/baby1/*.jpg
usage: sot_video.py [-h] [-cfg CONFIG] [-d DEVICE] [-v VIDEO] [-o OUTPUT]
                    [-s START_INDEX] [-r RESIZE] [-do]
                    [-i INIT_BBOX [INIT_BBOX ...]]
sot_video.py: error: unrecognized arguments: datasets/baby1/0002.jpg datasets/baby1/0003.jpg datasets/baby1/0004.jpg datasets/baby1/0005.jpg datasets/baby1/0006.jpg datasets/baby1/0007.jpg datasets/baby1/0008.jpg datasets/baby1/0009.jpg datasets/baby1/0010.jpg datasets/baby1/0011.jpg datasets/baby1/0013.jpg...""

I look forward to your reply！ Thank you!

**Comment by lzx1413** [comment]
you can try this 
```
python3 ./demo/main/video/sot_video.py --config 'experiments/siamfcpp/test/vot/siamfcpp_alexnet.yaml' --device cuda --video "datasets/baby1/*.jpg"
```

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
