### ISSUE TITLE
HI,I have a question about this project,can I run this program under Windows10?

### ISSUE THREAD

**Issue by fengege** [MegviiDetection/video_analyst#218]
HI,I have a question about this project,can I run this program under Windows10?

**Comment by MARMOTatZJU** [comment]
@fengege Theoretically, this project should not rely on dependencies that can not run on Windows 10, so the answer should be "yes".

If you encounter any package that is difficult to run on Windows10, you can try to tailor the code yourself (e.g. comment those incompatible import lines).

**Comment by MARMOTatZJU** [comment]
@fengege Pay attention to this issue, which is related to running segmentation on Win10: https://github.com/MegviiDetection/video_analyst/issues/204

However, it should not affect the running of visual tracking on Win10 as it is related to the package `shapely`.

**Comment by fengege** [comment]
Ok,thank you very much for your answer to my question.
