### ISSUE TITLE
Does the siamTiny have the pretrainedmodel?

### ISSUE THREAD

**Issue by zxyyxzz** [MegviiDetection/video_analyst#222]
Thanks for your implement of the single object tracking,  i have some questions about siamtiny：
1. Does the siamTiny have the pretrainedmodel?
2. siamtiny是不是经过模型剪枝后的模型？就是如果我单独去训它，达不到您代码里的效果？

**Comment by zxyyxzz** [comment]
@lzx1413

**Comment by zxyyxzz** [comment]
@MARMOTatZJU 您好，我单独训练Siamfcpp, 结果非常非常低，请问是要大模型剪枝吗？

**Comment by lzx1413** [comment]
siamtiny不是剪枝得到的模型，可以尝试使用alexnet+pretrain model进行训练正确性的测试

**Comment by zxyyxzz** [comment]
> siamtiny不是剪枝得到的模型，可以尝试使用alexnet+pretrain model进行训练正确性的测试

感谢您的答复，我还有几个问题：
1.那siamtiny需要有预训练模型吗？还是直接训就可以？
2.您训练siamtiny，用的几个数据集，训了多少的epoch?我是用了COCO，TrackingNet, Got10k.
3.我训练的时候loss一直下降, iou也在升高就是在otb2015测试的时候指标只有0.028

**Comment by lzx1413** [comment]
siamtiny应该没有使用预训练模型，你可以先使用下载的tiny模型测试一下，看测试流程对不对

**Comment by zxyyxzz** [comment]
> siamtiny应该没有使用预训练模型，你可以先使用下载的tiny模型测试一下，看测试流程对不对

我找到原因了，之前是我在训练的时候比测试的时候多做了一个归一化，谢谢你！~
