### ISSUE TITLE
Question abouyt online_classifier

### ISSUE THREAD

**Issue by YangC-1** [MegviiDetection/video_analyst#225]
Hi, could you please give some hints about the implementation of the _BaseClassifier_ in _base_classifier.py_? What does the BaseClassifier do in online tracking? Maybe some references will be of help also. I can not find anything related to the BaseClassifier in the original paper of SiamFC++. Thanks a lot.

**Comment by lzx1413** [comment]
They are from ATOM, please refer to https://github.com/visionml/pytracking
