### ISSUE TITLE
About how to reproduce siamfcpp VOT model?

### ISSUE THREAD

**Issue by sidney001** [MegviiDetection/video_analyst#234]
For the siamfcpp VOT model, we can download the link in MODEL_ZOO.md and find corresponding configs "experiments/siamfcpp/test/vot/" dir. But as to the training config of VOT models, I do find docs that "For VOT benchmark, models have been trained on ILSVRC-VID/DET, YoutubeBB, COCO, LaSOT, and GOT-10k (as described in our paper)" about it.  So the training config of fulldata is the VOT training config? Can you give me some thoughts? @MARMOTatZJU @lzx1413

**Comment by NrealLzx** [comment]
Yes, you are right. The full-dataset version is tested on VOT

**Comment by lzx1413** [comment]
Yes, you are right. The fulldata version is vot model.

**Comment by sidney001** [comment]
thx
