### ISSUE TITLE
training log

### ISSUE THREAD

**Issue by songdejia** [MegviiDetection/video_analyst#30]
Can u please provide the training log of Google-Net Got10K version ? thank u please

**Comment by lzx1413** [comment]
@MARMOTatZJU

**Comment by MARMOTatZJU** [comment]
@songdejia Do you mean the tensorboard log ?

**Comment by songdejia** [comment]
emmm , the final value of cls, ctr, reg, iou

**Comment by MARMOTatZJU** [comment]
@songdejia 
[tensorboard-siamfcpp_googlenet.zip](https://github.com/MegviiDetection/video_analyst/files/4312138/tensorboard-siamfcpp_googlenet.zip)
