### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by anchor666** [MegviiDetection/video_analyst#31]
Hello, if I use the got-10k data set provided by the official website, does the dataset need to be preprocessed before training? (for example, siamrpn + +, I need to do pre_crop 511 12 before training). If I want to add other training datasets, such as coco vid, is the configuration file of the datasets the same as that of got10K.py？Thank you very much for your answer

**Comment by lzx1413** [comment]
@anchor666  the got-10k does not need to be preprocessed in this project.  We do this process in the training process. If you want to add another dataset,  you can write a datasetxxx.py like other datasets in data/dataset/dataset_impl.  And you can just add your dataset in the config yaml file to use it.

**Comment by MARMOTatZJU** [comment]
@anchor666 May we close this issue since no further discussion persists?

**Comment by anchor666** [comment]
> @anchor666 May we close this issue since no further discussion persists?

Of course it can be closed，Thanks again！
