### ISSUE TITLE
YouTube-BB 数据集

### ISSUE THREAD

**Issue by hlyj1995** [MegviiDetection/video_analyst#32]
请问您有处理好的YouTube-BB 数据集的百度网盘么，从官方下载视频文件实在太大了，梯子的流量不够。

**Comment by lzx1413** [comment]
We will adopt [trackingnet](https://tracking-net.org/) rather than youtubebb dataset.  You can download it from the official website or we will upload it to cloud drives.

**Comment by eilo1234** [comment]
I also need trackingnet datasets, but I always make mistakes when I download them. Can you provide download links like Baidu cloud?

**Comment by laisimiao** [comment]
> 请问您有处理好的YouTube-BB 数据集的百度网盘么，从官方下载视频文件实在太大了，梯子的流量不够。

官网不就是几十MB吗，为什么说很大？
