### ISSUE TITLE
TrackingNet datasets?

### ISSUE THREAD

**Issue by eilo1234** [MegviiDetection/video_analyst#43]
I also need trackingnet datasets, but I always make mistakes when I download them. Can you provide download links like Baidu cloud drives?

**Comment by lzx1413** [comment]
We are uploading data to baiduyunpan now, Please keep tuned.

**Comment by eilo1234** [comment]
> We are uploading data to baiduyunpan now, Please keep tuned.
Thank you for your quick reply and the baiduyunpan link you will provide soon.
