### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by 627081385** [MegviiDetection/video_analyst#46]
which version of CUDA does the author use?
When I use CUDA10.1,2080ti,torch==1.4.0torchvision==0.5.0,
it will get the following error：
CUDNN_STATUS_EXECUTION_FAILED

**Comment by MARMOTatZJU** [comment]
@627081385 
We have the same configuration than you. What's your CUDNN version ? We use CUDNN==7.6.5.
BTW, consider reinstalling your PyTorch and see if things get better.

```Bash
pip3 install -U torch==1.4.0 torchvision==0.5.0
```

**Comment by MARMOTatZJU** [comment]
@627081385 Has your problem been resolved ?

**Comment by 627081385** [comment]
yes,I reinstalled the environment and solved it，thanks for you concern
