### ISSUE TITLE
can not train

### ISSUE THREAD

**Issue by DTM3302** [MegviiDetection/video_analyst#47]
when i run sh tools/train_test-googlent.sh, An error occurred：
![微信截图_20200321115759](https://user-images.githubusercontent.com/61957363/77218959-043d7d00-6b6c-11ea-8f8b-39e4f0177af5.png)
Where should I download these files？

**Comment by lzx1413** [comment]
The figure is crashed, please paste your error code here.

**Comment by lzx1413** [comment]
The download links can be found here https://github.com/MegviiDetection/video_analyst/blob/master/docs/SOT_MODEL_ZOO.md

**Comment by DTM3302** [comment]
ok，thanks

**Comment by MARMOTatZJU** [comment]
@DTM3302
This traceback is given by tester. Because your training was broken, the training did not reach epoch 19 and thus epoch-19.pkl has not heen dumped.
Could you please provide the trackeback given by the traininer (scroll up your scren ?)?

**Comment by DTM3302** [comment]
May be this problem:
 
![1584765268(1)](https://user-images.githubusercontent.com/61957363/77219419-947dc100-6b70-11ea-83f6-b234460ddacc.png)

**Comment by lzx1413** [comment]
gpu should be replaced by cuda, we will fix this bug soon.
