### ISSUE TITLE
TrackingNet baiduyunpan link?

### ISSUE THREAD

**Issue by eilo1234** [MegviiDetection/video_analyst#59]
Sorry to bother you again, can you provide TrackingNet datasets baiduyunpan download link? Because I haven't downloaded it successfully.

**Comment by lzx1413** [comment]
We haven't finished uploading this dataset on baiduyun now. But you can download some part of it from link: https://pan.baidu.com/s/1PXSRAqcw-KMfBIJYUtI4Aw code: nkb9

**Comment by eilo1234** [comment]
Thank you very much !

**Comment by MARMOTatZJU** [comment]
@eilo1234
It seems that you would like to perform the fulldata experiment. 

If this is the case, I would like to remind you the fact that the fulldata experiment is very "resource-consuming". For example, the fullldata experiment of googlenet will consume 32 cpu, 8 gpus, 64G memory on our cluster. And we also have trouble to perform it without internal dataprovider infrastructure of the company.

**Comment by eilo1234** [comment]
got it.Thank you very much for your remind.

**Comment by zhu2014yi** [comment]
> @eilo1234
> It seems that you would like to perform the fulldata experiment.
> 
> If this is the case, I would like to remind you the fact that the fulldata experiment is very "resource-consuming". For example, the fullldata experiment of googlenet will consume 32 cpu, 8 gpus, 64G memory on our cluster. And we also have trouble to perform it without internal dataprovider infrastructure of the company.

请问12核，双1080ti,64G RAM跑fulldata大概要几天

**Comment by zhu2014yi** [comment]
> @eilo1234
> It seems that you would like to perform the fulldata experiment.
> 
> If this is the case, I would like to remind you the fact that the fulldata experiment is very "resource-consuming". For example, the fullldata experiment of googlenet will consume 32 cpu, 8 gpus, 64G memory on our cluster. And we also have trouble to perform it without internal dataprovider infrastructure of the company.
请问你们是用多少张GPU多大RAM跑的，而且要跑多久？

**Comment by zhanght021** [comment]
@lzx1413 @MARMOTatZJU  Hi thanks for your uploading TrackingNet dataset ,  i download the TEST part, and unzip it ,and i met some problem
inflating: TEST/zips/Gw5FxWOjKUE_0.zip   bad CRC 8885bed5  (should be bd58d989)
inflating: TEST/zips/vbCFd2ppCgk_0.zip   bad CRC 9b04b0f6  (should be cdb3cc5f)
 in Gw5FxWOjKUE_0 , it lack of 281.jpg and 282.jpg
and in vbCFd2ppCgk_0,  it lack of 83.jpg

**Comment by MARMOTatZJU** [comment]
@zhanght021 When did you download it? We have just finished uploading on Baidudisk in the evening last Sunday.

**Comment by zhanght021** [comment]
@MARMOTatZJU  Yesterday afternoon，

**Comment by MARMOTatZJU** [comment]
@zhanght021 Both _Gw5FxWOjKUE_0 .zip_ and _vbCFd2ppCgk_0.zip_ passed the zip test. If it is convenient for you to redownload the files, consider redownloading TEST part and unzip again.
If it is not the case, I will reupload it later.

**Comment by zhanght021** [comment]
@MARMOTatZJU  Thanks a lot，I will try downloading again ，
