### ISSUE TITLE
tracking results by using fulldata

### ISSUE THREAD

**Issue by zhu2014yi** [MegviiDetection/video_analyst#61]
请问在使用fulldata之后在OTB100，VOT2018，VOT2019上面表现如何

**Comment by lzx1413** [comment]
vot2018 result can be found here https://github.com/MegviiDetection/video_analyst/blob/master/docs/SOT_MODEL_ZOO.md. The result of other bmks can be found from paper https://arxiv.org/abs/1911.06188. We will release them soon.

**Comment by zhu2014yi** [comment]
thanks

**Comment by zhu2014yi** [comment]
> vot2018 result can be found here https://github.com/MegviiDetection/video_analyst/blob/master/docs/SOT_MODEL_ZOO.md. The result of other bmks can be found from paper https://arxiv.org/abs/1911.06188. We will release them soon.

thanks
