### ISSUE TITLE
When do you public shufflenetv2x0.5, shufflenetv2x1.0 results on VOT2018?

### ISSUE THREAD

**Issue by ujsyehao** [MegviiDetection/video_analyst#63]
Thank you in advance!
We trained shufflenetv2x0.5, shufflenetv2x1.0 on VOT2018, **but the results are not consistent with our cognition**, So can you provide your results as a reference?

**Comment by lzx1413** [comment]
The models tested on VOT should be trained with full datasets config.  We only supply the  shufflenet with got-10k for now. How do you train the shufllenet based trackers?

**Comment by MARMOTatZJU** [comment]
@ujsyehao VOT2018 should not be used for training. It's for benchmarking instead.
ShuffleNet experiments were not within the published paper. We have only tested it on GOT-10k.

**Comment by ujsyehao** [comment]
@lzx1413 @MARMOTatZJU  We trained shufflenet0.5-based tracker with full datasets(use siamfcpp_shufflenetv2x0_5-trn.yaml) and tested it on VOT2018, but the EAO only reaches 0.29, it is lower than alexnet-based tracker.
It is not consistent with GOT10k results.

**Comment by lzx1413** [comment]
@ujsyehao  siamfcpp_shufflenetv2x0_5-trn.yaml only uses the got10k as train dataset. The alexnet based models for vot test are trained with full datasets(coco, lasot and so on). So it is reasonable that it has lower performance on vot compared with alextnet.

**Comment by ujsyehao** [comment]
@lzx1413 **We re-train shufflenet0.5 tracker on the full dataset.** So I am confused about your reply. you mean the hyper-param need modify?

**Comment by lzx1413** [comment]
@ujsyehao  Yes, all trackers tested on vot dataset need hyper-param optimize.

**Comment by ujsyehao** [comment]
@lzx1413 So Can you give me some advice?
Do you have a plan to train shufflenet tracker on a full dataset? 
We have doubts about the performance of shufflenet tracker on the VOT dataset.

**Comment by MARMOTatZJU** [comment]
@ujsyehao I think that it may be roughly the same as Alexnet (the best epoch, of course).

**Comment by ujsyehao** [comment]
@MARMOTatZJU but we trained and only reaches 0.298.

**Comment by MARMOTatZJU** [comment]
@ujsyehao Probably the hyper-parameters related to training (e.g. lr and weight_decay) need to be tuned. We didn't report performance for ShuffleNetV2, thus we have not carefully tuned them for fulldata.
Via our observation, SOT training is very sensible to hyper-parameters.

**Comment by MARMOTatZJU** [comment]
Closed as no further discussion. Feel free to reopen it again.
