### ISSUE TITLE
about setup

### ISSUE THREAD

**Issue by laisimiao** [MegviiDetection/video_analyst#64]
when i obey the guidelines in SOT_SETUP.md, after i `conda activate siamfcpp` and i surely in the conda virtual environment, and after i ran `pip3 install -U -r requirements.txt`，some packages always can't be installed successfully(although in terminal it shows they are installed successfully) beacause i import these packages, they return `ModuleNotFoundError`, so where are wrong?

**Comment by buaacarzp** [comment]
guy, you should think this problem by yourself, don't like a kid.
this problem maybe created by your IDE.




| |
Zp_ositive
|
|
邮箱：18811746117@163.com
|

Signature is customized by Netease Mail Master

On 04/17/2020 18:46, laisimiao wrote:

when i obey the guidelines in SOT_SETUP.md, after i conda activate siamfcpp and i surely in the conda virtual environment, and after i ran pip3 install -U -r requirements.txt，some packages always can't be installed successfully(although in terminal it shows they are installed successfully) beacause i import these packages, they return ModuleNotFoundError, so where are wrong?

**Comment by MARMOTatZJU** [comment]
@laisimiao Can you post the cmd log so that we can help you figure out the problem?

**Comment by MARMOTatZJU** [comment]
@laisimiao BTW, consider using virtualenv instead of conda?

**Comment by laisimiao** [comment]
my anaconda version is 5.2.0(python3.6.5), in base environment:
i comment two lines in requirements.txt(that is 'torch==1.4.0' and 'torchvision==0.5.0', because i want to install them in a local way later), this is terminal install log:
(base) lsm@lsm:~/video_analyst$ pip install -r requirements.txt 
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting tqdm (from -r requirements.txt (line 1))
  Downloading http://mirrors.aliyun.com/pypi/packages/4a/1c/6359be64e8301b84160f6f6f7936bbfaaa5e9a4eab6cbc681db07600b949/tqdm-4.45.0-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 15.9MB/s 
Requirement already satisfied: pylint in /home/lsm/anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (1.8.4)
Collecting yacs (from -r requirements.txt (line 3))
  Downloading http://mirrors.aliyun.com/pypi/packages/2f/51/9d613d67a8561a0cdf696c3909870f157ed85617fea3cff769bb7de09ef7/yacs-0.1.6-py3-none-any.whl
Requirement already satisfied: pillow in /home/lsm/anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (5.1.0)
Collecting Cython==0.27.3 (from -r requirements.txt (line 5))
  Downloading http://mirrors.aliyun.com/pypi/packages/e9/91/46cb3f4c73f1e96faa517f96e9d12de5b8c97d404c7ab71553da0e58c980/Cython-0.27.3-cp36-cp36m-manylinux1_x86_64.whl (3.1MB)
    100% |████████████████████████████████| 3.1MB 75.5MB/s 
Collecting yapf==0.28.0 (from -r requirements.txt (line 6))
  Downloading http://mirrors.aliyun.com/pypi/packages/79/22/d711c0803b6c3cc8c96eb54509f23fec1e3c078d5bfc6eb11094e762e7bc/yapf-0.28.0-py2.py3-none-any.whl (180kB)
    100% |████████████████████████████████| 184kB 12.5MB/s 
Collecting opencv-python==4.1.0.25 (from -r requirements.txt (line 7))
  Downloading http://mirrors.aliyun.com/pypi/packages/7b/d2/a2dbf83d4553ca6b3701d91d75e42fe50aea97acdc00652dca515749fb5d/opencv_python-4.1.0.25-cp36-cp36m-manylinux1_x86_64.whl (26.6MB)
    100% |████████████████████████████████| 26.6MB 12.9MB/s 
Collecting numpy==1.16.0 (from -r requirements.txt (line 8))
  Downloading http://mirrors.aliyun.com/pypi/packages/7b/74/54c5f9bb9bd4dae27a61ec1b39076a39d359b3fb7ba15da79ef23858a9d8/numpy-1.16.0-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 62.3MB/s 
Collecting colorama==0.3.7 (from -r requirements.txt (line 11))
  Downloading http://mirrors.aliyun.com/pypi/packages/b7/8e/ddb32ddaabd431813e180ca224e844bab8ad42fbb47ee07553f0ec44cd86/colorama-0.3.7-py2.py3-none-any.whl
Collecting numba==0.45.0 (from -r requirements.txt (line 12))
  Downloading http://mirrors.aliyun.com/pypi/packages/42/ff/ba2c7ee7140934de56baec3e8e7ca57f4709bb6260a5261749256ec5a0e9/numba-0.45.0-cp36-cp36m-manylinux1_x86_64.whl (3.5MB)
    100% |████████████████████████████████| 3.5MB 12.2MB/s 
Collecting matplotlib==3.0.0 (from -r requirements.txt (line 13))
  Downloading http://mirrors.aliyun.com/pypi/packages/ed/89/dd823436a5f8d5ca9304b51b554863bfd366ca84708d5812f5ee87c923bc/matplotlib-3.0.0-cp36-cp36m-manylinux1_x86_64.whl (12.8MB)
    100% |████████████████████████████████| 12.8MB 12.9MB/s 
Collecting wget==3.2 (from -r requirements.txt (line 14))
  Downloading http://mirrors.aliyun.com/pypi/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip
Collecting shapely==1.7.0 (from -r requirements.txt (line 15))
  Downloading http://mirrors.aliyun.com/pypi/packages/20/fa/c96d3461fda99ed8e82ff0b219ac2c8384694b4e640a611a1a8390ecd415/Shapely-1.7.0-cp36-cp36m-manylinux1_x86_64.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 11.8MB/s 
Collecting scipy==1.2.1 (from -r requirements.txt (line 16))
  Downloading http://mirrors.aliyun.com/pypi/packages/7f/5f/c48860704092933bf1c4c1574a8de1ffd16bf4fde8bab190d747598844b2/scipy-1.2.1-cp36-cp36m-manylinux1_x86_64.whl (24.8MB)
    100% |████████████████████████████████| 24.8MB 12.8MB/s 
Collecting tensorboard (from -r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/1d/fd/4f3ca1516cbb3713259ef229abd9314bba0077ef6070285dde0dd1ed21b2/tensorboard-2.2.1-py3-none-any.whl (3.0MB)
    100% |████████████████████████████████| 3.0MB 12.9MB/s 
Collecting future==0.18.2 (from -r requirements.txt (line 18))
Collecting loguru==0.4.1 (from -r requirements.txt (line 19))
  Downloading http://mirrors.aliyun.com/pypi/packages/b2/f4/2c8b94025c6e30bdb331c7ee628dc152771845aedff35f0365c2a4dacd42/loguru-0.4.1-py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 17.4MB/s 
Requirement already satisfied: astroid<2.0,>=1.6 in /home/lsm/anaconda3/lib/python3.6/site-packages (from pylint->-r requirements.txt (line 2)) (1.6.3)
Requirement already satisfied: six in /home/lsm/anaconda3/lib/python3.6/site-packages (from pylint->-r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: isort>=4.2.5 in /home/lsm/anaconda3/lib/python3.6/site-packages (from pylint->-r requirements.txt (line 2)) (4.3.4)
Requirement already satisfied: mccabe in /home/lsm/anaconda3/lib/python3.6/site-packages (from pylint->-r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: PyYAML in /home/lsm/anaconda3/lib/python3.6/site-packages (from yacs->-r requirements.txt (line 3)) (3.12)
Collecting llvmlite>=0.29.0dev0 (from numba==0.45.0->-r requirements.txt (line 12))
  Downloading http://mirrors.aliyun.com/pypi/packages/ad/bb/60d4033d56c9da36490af19caa6c794b72b8aef6f792fdfa8cb95d11e419/llvmlite-0.31.0-cp36-cp36m-manylinux1_x86_64.whl (20.2MB)
    100% |████████████████████████████████| 20.2MB 12.7MB/s 
Requirement already satisfied: python-dateutil>=2.1 in /home/lsm/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.0->-r requirements.txt (line 13)) (2.7.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/lsm/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.0->-r requirements.txt (line 13)) (2.2.0)
Requirement already satisfied: cycler>=0.10 in /home/lsm/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.0->-r requirements.txt (line 13)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/lsm/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.0->-r requirements.txt (line 13)) (1.0.1)
Collecting protobuf>=3.6.0 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/57/02/5432412c162989260fab61fa65e0a490c1872739eb91a659896e4d554b26/protobuf-3.11.3-cp36-cp36m-manylinux1_x86_64.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 13.0MB/s 
Collecting requests<3,>=2.21.0 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 14.5MB/s 
Collecting google-auth<2,>=1.6.3 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/4f/97/5e7083a5be4cbd1d928061c9d9cb3c070e55d5a15c563be41cb47b544807/google_auth-1.14.0-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 13.7MB/s 
Collecting tensorboard-plugin-wit>=1.6.0 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/51/cd/a0c1f9e4582ea64dddf76c1b808b318d01e3b858a51c715bffab1016ecc7/tensorboard_plugin_wit-1.6.0.post3-py3-none-any.whl (777kB)
    100% |████████████████████████████████| 778kB 12.0MB/s 
Requirement already satisfied: werkzeug>=0.11.15 in /home/lsm/anaconda3/lib/python3.6/site-packages (from tensorboard->-r requirements.txt (line 17)) (0.14.1)
Collecting setuptools>=41.0.0 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/a0/df/635cdb901ee4a8a42ec68e480c49f85f4c59e8816effbf57d9e6ee8b3588/setuptools-46.1.3-py3-none-any.whl (582kB)
    100% |████████████████████████████████| 583kB 12.0MB/s 
Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/7b/b8/88def36e74bee9fce511c9519571f4e485e890093ab7442284f4ffaef60b/google_auth_oauthlib-0.4.1-py2.py3-none-any.whl
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/lsm/anaconda3/lib/python3.6/site-packages (from tensorboard->-r requirements.txt (line 17)) (0.31.1)
Collecting markdown>=2.6.8 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/ab/c4/ba46d44855e6eb1770a12edace5a165a0c6de13349f592b9036257f3c3d3/Markdown-3.2.1-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 13.7MB/s 
Collecting absl-py>=0.4 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/1a/53/9243c600e047bd4c3df9e69cfabc1e8004a82cac2e0c484580a78a94ba2a/absl-py-0.9.0.tar.gz (104kB)
    100% |████████████████████████████████| 112kB 13.9MB/s 
Collecting grpcio>=1.24.3 (from tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/cf/7a/9744998129fce7e29c5f2d8b0f545913b7383e65d8366fc0ae98d11936af/grpcio-1.28.1.tar.gz (19.5MB)
    100% |████████████████████████████████| 19.5MB 5.7MB/s 
Collecting aiocontextvars>=0.2.0; python_version < "3.7" (from loguru==0.4.1->-r requirements.txt (line 19))
  Downloading http://mirrors.aliyun.com/pypi/packages/db/c1/7a723e8d988de0a2e623927396e54b6831b68cb80dce468c945b849a9385/aiocontextvars-0.2.2-py2.py3-none-any.whl
Requirement already satisfied: lazy_object_proxy in /home/lsm/anaconda3/lib/python3.6/site-packages (from astroid<2.0,>=1.6->pylint->-r requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: wrapt in /home/lsm/anaconda3/lib/python3.6/site-packages (from astroid<2.0,>=1.6->pylint->-r requirements.txt (line 2)) (1.10.11)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/lsm/anaconda3/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->-r requirements.txt (line 17)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/lsm/anaconda3/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->-r requirements.txt (line 17)) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /home/lsm/anaconda3/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->-r requirements.txt (line 17)) (2018.4.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/lsm/anaconda3/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->-r requirements.txt (line 17)) (1.22)
Collecting rsa<4.1,>=3.1.4 (from google-auth<2,>=1.6.3->tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.6.3->tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl (155kB)
    100% |████████████████████████████████| 163kB 13.2MB/s 
Collecting cachetools<5.0,>=2.0.0 (from google-auth<2,>=1.6.3->tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/b3/59/524ffb454d05001e2be74c14745b485681c6ed5f2e625f71d135704c0909/cachetools-4.1.0-py3-none-any.whl
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/a3/12/b92740d845ab62ea4edf04d2f4164d82532b5a0b03836d4d4e71c6f3d379/requests_oauthlib-1.3.0-py2.py3-none-any.whl
Collecting contextvars==2.4; python_version < "3.7" (from aiocontextvars>=0.2.0; python_version < "3.7"->loguru==0.4.1->-r requirements.txt (line 19))
  Downloading http://mirrors.aliyun.com/pypi/packages/83/96/55b82d9f13763be9d672622e1b8106c85acb83edd7cc2fa5bc67cd9877e9/contextvars-2.4.tar.gz
Collecting pyasn1>=0.1.3 (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 11.4MB/s 
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->-r requirements.txt (line 17))
  Downloading http://mirrors.aliyun.com/pypi/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl (147kB)
    100% |████████████████████████████████| 153kB 12.8MB/s 
Collecting immutables>=0.9 (from contextvars==2.4; python_version < "3.7"->aiocontextvars>=0.2.0; python_version < "3.7"->loguru==0.4.1->-r requirements.txt (line 19))
  Downloading http://mirrors.aliyun.com/pypi/packages/62/cc/3961b18a1a689a7e3232d923a8546cb901c49b4a33be6987c03a89175c4f/immutables-0.11-cp36-cp36m-manylinux1_x86_64.whl (92kB)
    100% |████████████████████████████████| 102kB 3.4MB/s 
Building wheels for collected packages: wget, absl-py, grpcio, contextvars
  Running setup.py bdist_wheel for wget ... done
  Stored in directory: /home/lsm/.cache/pip/wheels/cd/b4/2f/79420a8ca3e0c7111f6316afa3b2d64ae12c3acaa81a1224a8
  Running setup.py bdist_wheel for absl-py ... done
  Stored in directory: /home/lsm/.cache/pip/wheels/00/11/66/ee668d06ed8b8b5eb8a3a21c5cfc3478bdecad69631926b993
  Running setup.py bdist_wheel for grpcio ... done
  Stored in directory: /home/lsm/.cache/pip/wheels/cf/0f/02/92c1c29d576e0c69d290c1b9f59ae59228f72158b2b773624d
  Running setup.py bdist_wheel for contextvars ... done
  Stored in directory: /home/lsm/.cache/pip/wheels/87/99/7c/2febe42d3b9e666673e0318bb935c13561c8da35d83e37a3e9
Successfully built wget absl-py grpcio contextvars
distributed 1.21.8 requires msgpack, which is not installed.
Installing collected packages: tqdm, yacs, Cython, yapf, numpy, opencv-python, colorama, llvmlite, numba, matplotlib, wget, shapely, scipy, setuptools, protobuf, requests, pyasn1, rsa, pyasn1-modules, cachetools, google-auth, tensorboard-plugin-wit, oauthlib, requests-oauthlib, google-auth-oauthlib, markdown, absl-py, grpcio, tensorboard, future, immutables, contextvars, aiocontextvars, loguru
  Found existing installation: Cython 0.28.2
    Uninstalling Cython-0.28.2:
      Successfully uninstalled Cython-0.28.2
  Found existing installation: numpy 1.14.3
    Uninstalling numpy-1.14.3:
      Successfully uninstalled numpy-1.14.3
  Found existing installation: colorama 0.3.9
    Uninstalling colorama-0.3.9:
      Successfully uninstalled colorama-0.3.9
  Found existing installation: llvmlite 0.23.1
Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
***
**it seems no problem according to the log**, but when i enter the python interpreter in another terminal(i want to test whether they are installed sucessfully or not):
(base) lsm@lsm:~/下载/whl$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tqdm
>>> import pylint
>>> import yacs
>>> import tensorboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorboard'
>>> import tensorboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorboard'
>>> import pillow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pillow'
>>> import Cython
>>> import yapf
>>> import numpy
>>> numpy.__version__
'1.16.0'
>>> import colorama
>>> import numba
>>> import matplotlib
>>> import wget
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wget'
>>> import shapely
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'shapely'
>>> import scipy
>>> import future
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'future'
>>> import loguru
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'loguru'
some of them seems that they are not installed sucessfully.

**if i re-install them one by one, the import problem will disappear, i am confuse this phenomenon**thanks for your reply!

**Comment by MARMOTatZJU** [comment]
@laisimiao _llvm_ package failed to install, and all the installation operations have been canceled. 
I do not know either the reason for this. Just make sure that all packages installed successfully by viewing the output log.
As for your issue, you can search the solution for package _llvm_ by google search. Here I post some of the results:
```
https://www.jianshu.com/p/faa1ca4238ec
https://blog.csdn.net/u012654847/article/details/80875838
```

**Comment by laisimiao** [comment]
Thank you for your reply!
I found another little problem: it [SOT_SETUP](https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/SOT_SETUP.md), the name of pretrained model in weiyun link about alexnet is **alexnet-bn-md5_fa7cdefb48f41978cf35e8c4f1159cdc.pth**, but in website its name is **alexnet-nopad-bn-md5_fa7cdefb48f41978cf35e8c4f1159cdc.pkl**. 
Are they the same one or not? If so, should I rename it to the name like in website?

**Comment by MARMOTatZJU** [comment]
They are the same. Thank you for pointing it out. I have change the filename to "pkl" on Weiyun Disk & Google Drive.

Thanks,
Yinda
________________________________
De : laisimiao <notifications@github.com>
Envoyé : mercredi 6 mai 2020 11:14
À : MegviiDetection/video_analyst <video_analyst@noreply.github.com>
Cc : Yinda XU <ydxu_zju@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [MegviiDetection/video_analyst] about setup (#64)


Thank you for your reply!
I found another little problem: it SOT_SETUP<https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/SOT_SETUP.md>, the name of pretrained model in weiyun link about alexnet is alexnet-bn-md5_fa7cdefb48f41978cf35e8c4f1159cdc.pth, but in website its name is alexnet-nopad-bn-md5_fa7cdefb48f41978cf35e8c4f1159cdc.pkl.
Are they the same one or not? If so, should I rename it to the name like in website?
