### ISSUE TITLE
 SOT_SETUP.md

### ISSUE THREAD

**Issue by pengyuan101** [MegviiDetection/video_analyst#69]
sorry!your  SOT_SETUP.md is 404,can you upload a new  SOT_SETUP.md

**Comment by MARMOTatZJU** [comment]
@pengyuan101 Accessed successfully at my side.
![image](https://user-images.githubusercontent.com/32362315/79768912-0149ce00-835e-11ea-9851-ee68ba530edc.png)

**Comment by pengyuan101** [comment]
> @pengyuan101 Accessed successfully at my side.
> ![image](https://user-images.githubusercontent.com/32362315/79768912-0149ce00-835e-11ea-9851-ee68ba530edc.png)

OK,thanks for your reply!I have solved this problem by directly visiting https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/SOT_SETUP.md

**Comment by pengyuan101** [comment]
The link of SOT_SETUP.md in your readme is https://github.com/MegviiDetection/video_analyst/blob/master/docs/SOT_SETUP.md .but your SOT_SETUP.md is actually in https://github.com/MegviiDetection/video_analyst/blob/master/docs/TUTORIALS/SOT_SETUP.md   I thinks there is some bugs,or maybe my problems .thanks again!!

**Comment by MARMOTatZJU** [comment]
@pengyuan101  Thanks a lot for pointing it out. Fixed in [this commit](https://github.com/MegviiDetection/video_analyst/commit/3fb8c01f4d4aab1d47ad4765a43e8d8c2191f516) on master branch.

**Comment by MARMOTatZJU** [comment]
Link fixed, issue closed. Feel free to reopen it if you find other broken links.
