### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by zhu2014yi** [MegviiDetection/video_analyst#77]
请问full data你们是用多少张GPU训练多少小时

**Comment by MARMOTatZJU** [comment]
@zhu2014yi  We haven't conducted training on any individual PC. Experiments have always been conducted on cloud clusters and its elapsed time can not be used as references for the training on individual PC.

However, as an estimate, for siamfcpp-googlenet, it takes around 20 hours (e.g. ~1 hour per epoch) to train on a machine with 4 GPUs. 

For full data experiments, the bottleneck should lie in the data provider part.

**Comment by zhu2014yi** [comment]
> @zhu2014yi We haven't conducted training on any individual PC. Experiments have always been conducted on cloud clusters and its elapsed time can not be used as references for the training on individual PC.
> 
> However, as an estimate, for siamfcpp-googlenet, it takes around 20 hours (e.g. ~1 hour per epoch) to train on a machine with 4 GPUs.
> 
> For full data experiments, the bottleneck should lie in the data provider part.

thanks
