### ISSUE TITLE
RuntimeError: Shared memory manager connection has timed out at /tmp/pip-req-build-ufslq_a9/torch/lib/libshm/core.cpp:99

### ISSUE THREAD

**Issue by Wenqian1228** [MegviiDetection/video_analyst#78]
## ❓ Questions and Help

when I train on the default config, after a few epochs,  I run into this error

> epoch 5, lr: 7.1e-02, cls: 0.089, ctr: 0.030, reg: 0.889, iou: 0.756, data: 7.5e-04, fwd: 3.0e-01, bwd: 1.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.089, ctr: 0.030, reg: 0.889, iou: 0.756, data: 7.5e-04, fwd: 3.0e-01, bwd: 1.5e-01, optim
epoch 5, lr: 7.1e-02, cls: 0.093, ctr: 0.030, reg: 0.877, iou: 0.759, data: 1.9e+01, fwd: 1.3e+00, bwd: 2.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.093, ctr: 0.030, reg: 0.877, iou: 0.759, data: 1.9e+01, fwd: 1.3e+00, bwd: 2.5e-01, optim
epoch 5, lr: 7.1e-02, cls: 0.090, ctr: 0.031, reg: 0.942, iou: 0.745, data: 1.2e-04, fwd: 9.9e-01, bwd: 1.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.090, ctr: 0.031, reg: 0.942, iou: 0.745, data: 1.2e-04, fwd: 9.9e-01, bwd: 1.5e-01, optim
epoch 5, lr: 7.1e-02, cls: 0.093, ctr: 0.031, reg: 0.887, iou: 0.757, data: 1.2e-04, fwd: 3.0e-01, bwd: 1.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.093, ctr: 0.031, reg: 0.887, iou: 0.757, data: 1.2e-04, fwd: 3.0e-01, bwd: 1.5e-01, optim
epoch 5, lr: 7.1e-02, cls: 0.098, ctr: 0.035, reg: 0.886, iou: 0.756, data: 1.1e-04, fwd: 3.0e-01, bwd: 1.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.098, ctr: 0.035, reg: 0.886, iou: 0.756, data: 1.1e-04, fwd: 3.0e-01, bwd: 1.5e-01, optim
epoch 5, lr: 7.1e-02, cls: 0.100, ctr: 0.033, reg: 0.897, iou: 0.754, data: 9.2e-05, fwd: 3.0e-01, bwd: 1.5e-01, optimepoch 5, lr: 7.1e-02, cls: 0.100, ctr: 0.033, reg: 0.897, iou: 0.754, data: 9.2e-05, fwd: 3.0e-01, bwd: 1.5e-01, optim
: 2.2e-01, :  18%|█▊        | 106/585 [04:24<20:47,  2.60s/it]Traceback (most recent call last):
  File "./main/train.py", line 111, in <module>
    trainer.train()
  File "/mnt/lustre/zhaowenqian/tracking/video_analyst-master/videoanalyst/engine/trainer/trainer_impl/regular_trainer.py", line 100, in train
    training_data = next(self._dataloader)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/mnt/lustre/zhaowenqian/anaconda3/lib/python3.7/site-packages/torch/storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Shared memory manager connection has timed out at /tmp/pip-req-build-ufslq_a9/torch/lib/libshm/core.cpp:99

**RuntimeError: Shared memory manager connection has timed out at /tmp/pip-req-build-ufslq_a9/torch/lib/libshm/core.cpp:99**

which I cannot locate where the problem is

**Comment by Wenqian1228** [comment]
I was running with pytorch 1.4.0 and torchvsion 5.0

**Comment by MARMOTatZJU** [comment]
@Wenqian1228 Try halve the num_workers. This error is related to the memory consumption.

**Comment by MARMOTatZJU** [comment]
@Wenqian1228 For fulldata experiment, you should have at least 64G memory, according to our experiences.

**Comment by Wenqian1228** [comment]
> @Wenqian1228 For fulldata experiment, you should have at least 64G memory, according to our experiences.

I am still confused here. I have memory larger than 64g and I am only training on Got10k dataset , and I checked my memory usage which still has a lot of free memory left during training. Plus I have tried halving the num_workers already and still it broke down with same error. could it be other problem?

**Comment by MARMOTatZJU** [comment]
@Wenqian1228 What's your CUDA version? torch==1.4.0 torchvision==0.5.0, requires CUDA==10.1 . Or you may need to recompile torch. 
We have encountered a similar problem under CUDA==10.0 . It was fixed by changing to CUDA==10.1.

**Comment by MARMOTatZJU** [comment]
@Wenqian1228 The number of iterations per epoch is 585? With our provided config file, it should be 1171. Have you changed by your self?  

BTW, consider pull the latest master branch down. We've been making effort to refine the code recently.

**Comment by Wenqian1228** [comment]
I am sorry I didn't explain clearly here I doubled the batch size, but I have tried many num_worker/batch_size combinations, and they all end up with same error

**Comment by Wenqian1228** [comment]
> @Wenqian1228 The number of iterations per epoch is 585? With our provided config file, it should be 1171. Have you changed by your self?
> 
> BTW, consider pull the latest master branch down. We've been making effort to refine the code recently.

Can I add you on WeChat and have some discussion since I have some further questions?

**Comment by MARMOTatZJU** [comment]
@Wenqian1228 Search me on Linkedin. There is my WeChat QR code there.

(not convenient to post directly my wechat contact here on github, sorry).
