### ISSUE TITLE
Where can we find the tracking results of siamfc++?

### ISSUE THREAD

**Issue by jcaha** [MegviiDetection/video_analyst#8]
Have you released tracking results of siamfc++ and where can we find them? Thanks for your great work.

**Comment by MARMOTatZJU** [comment]
There are download links at the top of [MODEL_ZOO.md](https://github.com/MegviiDetection/video_analyst/blob/master/docs/MODEL_ZOO.md) and in these links, you can find results for VOT2018 and GOT-10k under _SiamFCpp/Results_. 
Feel free to tell if you need results for other benchmarks.
Goodluck.

**Comment by jcaha** [comment]
Thanks for your reply.
Could you provide us the results for LaSOT?

**Comment by MARMOTatZJU** [comment]
@jcaha It is under preparation. You will get informed in this thread as soon as it is ready.

**Comment by MARMOTatZJU** [comment]
@jcaha LaSOT results have been added and you can get them from download links in [this page](https://github.com/MegviiDetection/video_analyst/blob/master/docs/MODEL_ZOO.md).

**Comment by jcaha** [comment]
Thanks for your release, it helps us a lot.
