### ISSUE TITLE
about training strategy

### ISSUE THREAD

**Issue by laisimiao** [MegviiDetection/video_analyst#88]
Hello, I want to ask two questions:
1. It seems the training strategy in this repo yaml isn't exactly same as that in paper, maybe be the difference between internal framework and PyTorch, so you choose the better performance cfg for us in this repo yaml file?
2. Does the yaml file whose name doesn't include 'dist' prepare for **single GPU machine** training? And if I have a machine which just has single GPU and less CPU threads, can you give some suggestions where should I modify in the cfg file? 
Sincerely appreciate for any help!!

**Comment by MARMOTatZJU** [comment]
1. The components are the same for paper and this repo (e.g. warming-up / cosine annealing), but some hyper-parameters (e.g. epochs for warming-up) have been modified for better stability. I dont think they will change the performance a lot. May be in the future there will be some autoML algorithm to automatically finetune them.

2. If you only have one GPU, choose config file without "dist". However, the difference between wt dist and wo dist is that the former uses PyTorch DDP while the latter does not.

**Comment by laisimiao** [comment]
> 1. The components are the same for paper and this repo (e.g. warming-up / cosine annealing), but some hyper-parameters (e.g. epochs for warming-up) have been modified for better stability. I dont think they will change the performance a lot. May be in the future there will be some autoML algorithm to automatically finetune them.
> 
> 
> 
> 2. If you only have one GPU, choose config file without "dist". However, the difference between wt dist and wo dist is that the former uses PyTorch DDP while the latter does not.

Thanks, I will do more research with this repo because I use them for my graduate design(I have read about one third of repo).Again, thank you!

**Comment by laisimiao** [comment]
Hi, I have noticed it can't finish the whole training in my machine:
`i7-4700 NVIDIA TITAN XP 32GB RAM`
And I modify some cfgs in train CfgNode in *experiments/siamfcpp/train/got10k/siamfcpp_alexnet-trn-.yaml*:
```
num_processes: 2 -> 1 # due to single GPU
num_workers: 32 -> 4 # due to CPU
minibatch: 32 -> 8 # actually GPU ram is enough for 32 even 64
```
I noticed in training, the cache/buffer will increase and free ram decrease( although it has set *pin_memory* to **False** and modify as above):
```
top - 11:09:12 up 1 day, 14:38,  3 users,  load average: 4.62, 4.75, 4.73
任务: 339 total,   2 running, 272 sleeping,   0 stopped,   0 zombie
%Cpu(s): 33.7 us,  2.4 sy,  0.0 ni, 45.8 id, 16.5 wa,  0.0 hi,  1.5 si,  0.0 st
KiB Mem : 32614456 total,  4612940 free,  6059936 used, 21941580 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used. 25894152 avail Mem

top - 11:12:37 up 1 day, 14:41,  3 users,  load average: 4.70, 4.75, 4.73
任务: 339 total,   3 running, 271 sleeping,   0 stopped,   0 zombie
%Cpu(s): 32.5 us,  1.9 sy,  0.0 ni, 50.5 id, 14.3 wa,  0.0 hi,  1.0 si,  0.0 st
KiB Mem : 32614456 total,  4007304 free,  6088440 used, 22518712 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used. 25834524 avail Mem
# following is when i stop training, but it seems it doesn't release the buff/cache, why?
top - 11:14:23 up 1 day, 14:43,  3 users,  load average: 0.98, 3.46, 4.27
%Cpu(s):  0.2 us,  0.3 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu(s):  0.1 us,  0.3 sy,  0.0 ni, 99.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32614456 total,  7714884 free,  2386116 used, 22513456 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used. 29574356 avail Mem
``` 
So during whole training, the real bottleneck is not size of GPU ram or CPU threads, but RAM!
Could you tell me which part result in the increasing of buff/cache(after I look some infos, may due to many IO operations??) and how can I finish whole training in my poor machine( I also have a stronger machine: 2 GPUS and i7-8th, but I decide to find problem in my own machine firstly, if not it will happen again in this stronger machine)
---
Besides, after stopping training( I have not try this during training), I use command you mentioned in #25 and it looks like it:
```
tmpfs            16G   65M   16G    1% /dev/shm
tmpfs            16G   65M   16G    1% /dev/shm
```

**Comment by MARMOTatZJU** [comment]
I recommand using smaller _num_workers_ (even 2 or 1)
Better not to change minibatch size as it may influence final performance of your trained model.

**Comment by lzx1413** [comment]
I think it's may be better to replace the target generation with pytorch code which can be processesed with GPU.

**Comment by laisimiao** [comment]
@lzx1413 @MARMOTatZJU Oh, I found cache won't increase all the time(up to about 23GB). My failure reason is the high cpu temperature so the machine automaticlly close. I just try train one epoch and wait for a moment and then resume train. Or I use less *num_workers*.
I really hope you can optim codes that less operations needed  for CPU and optim data load operations in the future(benefit for us that has no strong hardware), thanks.
BTW, which paramters will influence the usage of RAM(batch size?)

**Comment by lzx1413** [comment]
Thanks for your suggestion. We will consider that in future work. The usage of RAM is mostly influenced by batch size and the number of worker in dataloader and the size of datafiles.

**Comment by lzx1413** [comment]
Feel free to reopen this issue if you have any relative questions.
