### ISSUE TITLE
SAT Test Problem

### ISSUE THREAD

**Issue by DTM3302** [MegviiDetection/video_analyst#89]
When I use python3 ./main/test.py --config 'experiments/sat/test/sat_res50-davis17.yaml' to test model. Finally,it output the J&F-Mean, But when i check the mask,It's just a black background,like this:
![00000](https://user-images.githubusercontent.com/61957363/81494822-3f436d80-92de-11ea-8c97-8895cf1adfb8.png)

**Comment by lzx1413** [comment]
The mask is a matrix of labels such as 0,1,2,3, so it is almost invisible. Ypu can get the visible results by set the save_video True in tester config.

**Comment by DTM3302** [comment]
ok，thanks！it works pretty well
