### ISSUE TITLE
some advice about sot video demo

### ISSUE THREAD

**Issue by laisimiao** [MegviiDetection/video_analyst#96]
Hello @MARMOTatZJU @lzx1413 Thanks for your wonderful work and open codes.I have try to use sot video demo(demo/main/video/sot_video.py) and give you some feedback so that you can improve or fix them:
- in [line66](https://github.com/MegviiDetection/video_analyst/blob/master/demo/main/video/sot_video.py#L66), it should be ''dump_only" not "dump-only";
- After [line157](https://github.com/MegviiDetection/video_analyst/blob/master/demo/main/video/sot_video.pyL157) it should add another line:`cv2.waitKey(1)` so the track result frame will be showed correctly, otherwise it's just a white window;
- For third demo way(that is, with extracted image files), don't forget to add "-i " params to define object location in initial frame and when use param "--video", don't forget to add **quotation marks** to path;
- the last is that for test image whose size is less than 128×128, the *template* can't be displayed on the left-top of current frame. If in future work it had better use proportionate size not fixed size.
Above are my advice. Thanks again!

**Comment by lzx1413** [comment]
Thanks for you suggestions. A PR is welcome  with these refinements.
